# Declarations of what the client adds to every script's builtins, for editors only: Pylance and Pyright
# read this file, the client never does. See docs/ScriptingApi.md for what each one does.

from typing import Any, Callable, Generator, Generic, Optional, Sequence, TypeVar, Union

Point = tuple[int, int]
T = TypeVar('T')
# What a wait yields to the host; use it with yield from, which gives the wait's result.
Wait = Generator[Any, None, T]

settings: "SettingsBag"

COMBAT_TICKS: int
INVENTORY: int
EQUIPMENT: int
BANK: int
BANK_INVENTORY: int
INVENTORY_SIZE: int
ATTACK: int
DEFENCE: int
STRENGTH: int
HITPOINTS: int
RANGED: int
PRAYER: int
MAGIC: int
COOKING: int
WOODCUTTING: int
FLETCHING: int
FISHING: int
FIREMAKING: int
CRAFTING: int
SMITHING: int
MINING: int
HERBLORE: int
AGILITY: int
THIEVING: int
RUNECRAFT: int
LAYER_WALL: int
LAYER_WALL_DECOR: int
LAYER_GROUND: int
LAYER_GROUND_DECOR: int

# World objects. Each is a snapshot of when it was found; valid() asks whether it's still there.

# An option's text as the menu shows it, or its number, 1 to 5.
Action = Union[str, int]

class _Located:
    def tile(self) -> "Tile": ...
    def distance(self) -> int: ...
    def actions(self) -> list[str]: ...

class Npc(_Located):
    index: int
    id: int
    name: Optional[str]
    level: int
    size: int
    in_combat: bool
    health: int
    max_health: int
    animation: int
    moving: bool
    target: Optional[tuple[str, int]]
    def interact(self, action: Action) -> bool: ...
    def valid(self) -> bool: ...
    def network_tile(self) -> "Tile": ...
    def targets_me(self) -> bool: ...
    def targets_another_player(self) -> bool: ...

class Player(_Located):
    index: int
    name: Optional[str]
    combat_level: int
    in_combat: bool
    health: int
    max_health: int
    animation: int
    moving: bool
    target: Optional[tuple[str, int]]
    def interact(self, action: Action) -> bool: ...
    def valid(self) -> bool: ...
    def targets_me(self) -> bool: ...

class Loc(_Located):
    id: int
    name: Optional[str]
    shape: int
    angle: int
    layer: int
    changed: bool
    def interact(self, action: Action) -> bool: ...
    def interact_via(self, points: Sequence[Point], action: Action) -> bool: ...
    def valid(self) -> bool: ...

class GroundItem(_Located):
    id: int
    name: Optional[str]
    count: int
    def interact(self, action: Action) -> bool: ...
    def valid(self) -> bool: ...

class InvItem:
    id: int
    name: Optional[str]
    count: int
    slot: int
    com: int
    noted: bool
    def actions(self) -> list[str]: ...
    def interact(self, action: Action) -> bool: ...
    def use_on(self, target: Union["InvItem", Npc, Player, Loc, GroundItem]) -> bool: ...

E = TypeVar('E')

class EntityQuery(Generic[E]):
    def name(self, *names: Union[str, Sequence[str]]) -> "EntityQuery[E]": ...
    def id(self, *ids: Union[int, Sequence[int]]) -> "EntityQuery[E]": ...
    def action(self, action: str) -> "EntityQuery[E]": ...
    def within(self, dist: int) -> "EntityQuery[E]": ...
    def within_of(self, origin: Any, dist: int) -> "EntityQuery[E]": ...
    def inside(self, area: Any) -> "EntityQuery[E]": ...
    def layer(self, layer: int) -> "EntityQuery[E]": ...
    def reachable(self) -> "EntityQuery[E]": ...
    def where(self, predicate: Callable[[E], bool]) -> "EntityQuery[E]": ...
    def results(self) -> list[E]: ...
    def nearest(self) -> Optional[E]: ...
    def nearest_prefer_local(self, prefer_radius: int) -> Optional[E]: ...
    def first(self) -> Optional[E]: ...
    def exists(self) -> bool: ...
    def count(self) -> int: ...

class _Npcs:
    def query(self) -> EntityQuery[Npc]: ...
    def all(self) -> list[Npc]: ...
    def get(self, index: int) -> Optional[Npc]: ...
    def nearest(self, count: int = 1) -> list[Npc]: ...

class _Players:
    def query(self) -> EntityQuery[Player]: ...
    def all(self) -> list[Player]: ...
    def local(self) -> Player: ...

class _Locs:
    def query(self) -> EntityQuery[Loc]: ...
    def at(self, tile: Any, layer: Optional[int] = None) -> Optional[Loc]: ...

class _GroundItems:
    def query(self) -> EntityQuery[GroundItem]: ...

npcs: _Npcs
players: _Players
locs: _Locs
ground_items: _GroundItems

class NpcType:
    id: int
    name: Optional[str]
    examine: Optional[str]
    ops: list[Optional[str]]
    size: int
    combat_level: Optional[int]

class ItemType:
    id: int
    name: Optional[str]
    examine: Optional[str]
    ops: list[Optional[str]]
    inventory_ops: list[Optional[str]]
    stackable: bool
    members: bool
    value: int
    note_of: Optional[int]

class LocType:
    id: int
    name: Optional[str]
    examine: Optional[str]
    ops: list[Optional[str]]
    width: int
    length: int
    blocks_walk: bool
    blocks_projectiles: bool

# Settings

class SettingDef:
    """One setting of a schema. type is 'boolean', 'number', 'string', 'string[]' or 'tile'."""
    def __init__(self, type: str = ..., default: Any = None, label: Optional[str] = None, min: Optional[float] = None,
                 max: Optional[float] = None, help: Optional[str] = None, options: Optional[list[str]] = None,
                 option_labels: Optional[dict[str, str]] = None, group: Optional[str] = None) -> None: ...

class SettingsBag:
    def __getattr__(self, name: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def bool(self, key: str, fallback: bool = False) -> bool: ...
    def num(self, key: str, fallback: float = 0) -> float: ...
    def str(self, key: str, fallback: str = '') -> str: ...
    def list(self, key: str, fallback: Optional[list[str]] = None) -> list[str]: ...
    def tile(self, key: str, fallback: "Tile") -> "Tile": ...
    def raw(self) -> dict[str, Any]: ...

# Geometry

class Tile:
    x: int
    z: int
    level: int
    def __init__(self, x: int, z: int, level: int = 0) -> None: ...
    @staticmethod
    def from_tile(tile: Any) -> "Tile": ...
    def distance_to(self, other: Any) -> int: ...
    def translate(self, dx: int, dz: int) -> "Tile": ...
    def equals(self, other: Any) -> bool: ...

class Area:
    @staticmethod
    def rectangular(a: Any, b: Any) -> "Area": ...
    @staticmethod
    def circular(center: Any, radius: int) -> "Area": ...
    @staticmethod
    def polygon(points: Sequence[Point], level: int = 0) -> "Area": ...
    def contains(self, tile: Any) -> bool: ...
    def get_random_tile(self) -> Tile: ...

# Events

class Event:
    """The payload of tick, chat_message, skill_xp, skill_level, inventory_changed, varp_changed and
    script_finish, with one attribute per field."""
    def __getattr__(self, name: str) -> Any: ...

class _EventBus:
    def on(self, event: str, callback: Callable[..., Any]) -> Callable[[], None]: ...
    def off(self, event: str, callback: Callable[..., Any]) -> None: ...

events: _EventBus

# Waiting

class _Execution:
    def delay(self, ms: int) -> Wait[None]: ...
    def delay_ticks(self, n: int) -> Wait[None]: ...
    def delay_until(self, cond: Callable[[], bool], timeout_ms: int = 6000) -> Wait[bool]: ...
    def delay_until_ticks(self, cond: Callable[[], bool], max_ticks: int) -> Wait[bool]: ...
    def note_progress(self) -> None: ...

execution: _Execution

# Bots

class AbstractBot:
    loop_delay: int
    loop_cadence: Optional[dict[str, Any]]
    settings: SettingsBag
    def log(self, *args: Any) -> None: ...
    def on(self, event: str, callback: Callable[..., Any]) -> None: ...
    def request_finish(self, reason: str) -> None: ...
    def grind_targets(self) -> list[str]: ...
    def ignored_randoms(self) -> list[str]: ...

class LoopingBot(AbstractBot):
    def loop(self) -> Union[int, None, Wait[Optional[int]]]: ...

class Task:
    label: Optional[str]
    def __init__(self, validate: Optional[Callable[[], Any]] = None, execute: Optional[Callable[[], Any]] = None, label: Optional[str] = None) -> None: ...
    def validate(self) -> Any: ...
    def execute(self) -> Any: ...

class TaskBot(LoopingBot):
    active_task_name: Optional[str]
    def add(self, *tasks: Any) -> None: ...

class BranchTask:
    def validate(self) -> bool: ...
    def success(self) -> Union["BranchTask", "LeafTask"]: ...
    def failure(self) -> Union["BranchTask", "LeafTask"]: ...

class LeafTask:
    def execute(self) -> Any: ...

class TreeBot(LoopingBot):
    def root(self) -> Union[BranchTask, LeafTask]: ...

class BotManifest:
    name: str
    create: Callable[[], AbstractBot]
    settings_schema: Optional[dict[str, SettingDef]]

def define_bot(name: str = ..., create: Callable[[], AbstractBot] = ..., description: Optional[str] = None,
               version: Optional[str] = None, category: Optional[str] = None, tags: Optional[list[str]] = None,
               settings_schema: Optional[dict[str, SettingDef]] = None) -> BotManifest: ...
def resolve_loop_cadence(loop_delay_ms: int, override: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...

# Items

class _Inventory:
    def items(self) -> list[InvItem]: ...
    def first(self, name: str) -> Optional[InvItem]: ...
    def contains(self, name: str) -> bool: ...
    def count(self, name: str) -> int: ...
    def count_by_id(self, id: int) -> int: ...
    def used(self) -> int: ...
    def free(self) -> int: ...
    def is_full(self) -> bool: ...

class _Equipment:
    def items(self) -> list[InvItem]: ...
    def contains(self, name: str) -> bool: ...
    def equip(self, name: str) -> Wait[bool]: ...
    def unequip(self, name: str) -> Wait[bool]: ...

inventory: _Inventory
equipment: _Equipment

# You and the game

class _Game:
    def ingame(self) -> bool: ...
    def tile(self) -> Optional[Tile]: ...
    def energy(self) -> int: ...
    def run_enabled(self) -> bool: ...
    def set_run(self, on: bool) -> None: ...
    def weight(self) -> int: ...
    def in_combat(self) -> bool: ...
    def animating(self) -> bool: ...
    def moving(self) -> bool: ...
    def tick(self) -> int: ...
    def my_name(self) -> Optional[str]: ...
    def combat_level(self) -> int: ...

class _Skills:
    def index(self, name: str) -> int: ...
    def level(self, name: str) -> int: ...
    def effective(self, name: str) -> int: ...
    def xp(self, name: str) -> int: ...
    def hp_fraction(self) -> float: ...

class _Reader:
    def varp(self, id: int) -> int: ...
    def pid(self) -> int: ...
    def main_modal(self) -> int: ...
    def side_modal(self) -> int: ...
    def chat_modal(self) -> int: ...
    def interface_open(self, id: int) -> bool: ...
    def component_text(self, com: int) -> Optional[str]: ...
    def count_dialog_open(self) -> bool: ...
    def inventory(self, com: int) -> list[InvItem]: ...
    def npc_type(self, id: int) -> Optional[NpcType]: ...
    def item_type(self, id: int) -> Optional[ItemType]: ...
    def loc_type(self, id: int) -> Optional[LocType]: ...

class _Chat:
    def say(self, text: str) -> None: ...
    def send_pm(self, name: str, text: str) -> None: ...
    def command(self, text: str) -> None: ...

class _Friends:
    def list(self) -> list[tuple[str, int]]: ...
    def add(self, name: str) -> None: ...
    def remove(self, name: str) -> None: ...

class _Ignores:
    def list(self) -> list[str]: ...
    def add(self, name: str) -> None: ...
    def remove(self, name: str) -> None: ...

class _DirectNavigator:
    def walk(self, dest: Any, run: bool = False) -> bool: ...
    def walk_to(self, dest: Any, radius: int = 2, timeout_ms: int = 45000, run: bool = False) -> Wait[bool]: ...
    def walk_path(self, points: Sequence[Point], run: bool = False) -> None: ...
    def reachable(self, dest: Any) -> bool: ...
    def path(self, dest: Any) -> Optional[list[Tile]]: ...
    def destination(self) -> Optional[Tile]: ...

game: _Game
skills: _Skills
reader: _Reader
chat: _Chat
friends: _Friends
ignores: _Ignores
direct_navigator: _DirectNavigator

# Control

def log(*args: Any) -> None: ...
def debug(*args: Any) -> None: ...
def stop_script() -> None: ...
def stop_account() -> None: ...
def send_bot_message(username: str, message: Any) -> bool: ...

# Until the phases that replace them (docs/BotApiDesign.md §14): interfaces and magic by component id.

def click_button(com: int) -> None: ...
def continue_dialogue() -> None: ...
def answer_count(value: int) -> None: ...
def close_interfaces() -> None: ...
def inv_button(item: InvItem, op: int) -> bool: ...
def move_item(com: int, from_slot: int, to_slot: int) -> None: ...
def cast_on_npc(spell: int, npc: Union[Npc, int]) -> bool: ...
def cast_on_player(spell: int, player: Union[Player, int]) -> bool: ...
def cast_on_loc(spell: int, id: int, x: int, z: int) -> None: ...
def cast_on_ground_item(spell: int, ground_item: GroundItem) -> bool: ...
def cast_on_item(spell: int, item: InvItem) -> bool: ...
