# Declarations of what the client adds to every script's builtins, for editors only: Pylance and Pyright
# read this file, the client never does. See docs/ScriptingApi.md for what each one does.

from typing import Any, Callable, Generator, Generic, Optional, Sequence, TypeVar, Union

Point = tuple[int, int]
T = TypeVar('T')
# What a wait yields to the host; use it with yield from, which gives the wait's result.
Wait = Generator[Any, None, T]

settings: "SettingsBag"

COMBAT_TICKS: int
INVENTORY: int
EQUIPMENT: int
BANK: int
BANK_INVENTORY: int
INVENTORY_SIZE: int
ATTACK: int
DEFENCE: int
STRENGTH: int
HITPOINTS: int
RANGED: int
PRAYER: int
MAGIC: int
COOKING: int
WOODCUTTING: int
FLETCHING: int
FISHING: int
FIREMAKING: int
CRAFTING: int
SMITHING: int
MINING: int
HERBLORE: int
AGILITY: int
THIEVING: int
RUNECRAFT: int
LAYER_WALL: int
LAYER_WALL_DECOR: int
LAYER_GROUND: int
LAYER_GROUND_DECOR: int

# World objects. Each is a snapshot of when it was found; valid() asks whether it's still there.

# An option's text as the menu shows it, or its number, 1 to 5.
Action = Union[str, int]

class _Located:
    def tile(self) -> "Tile": ...
    def distance(self) -> int: ...
    def actions(self) -> list[str]: ...

class Npc(_Located):
    index: int
    id: int
    name: Optional[str]
    level: int
    size: int
    in_combat: bool
    health: int
    max_health: int
    animation: int
    moving: bool
    target: Optional[tuple[str, int]]
    def interact(self, action: Action) -> bool: ...
    def valid(self) -> bool: ...
    def network_tile(self) -> "Tile": ...
    def targets_me(self) -> bool: ...
    def targets_another_player(self) -> bool: ...

class Player(_Located):
    index: int
    name: Optional[str]
    combat_level: int
    in_combat: bool
    health: int
    max_health: int
    animation: int
    moving: bool
    target: Optional[tuple[str, int]]
    def interact(self, action: Action) -> bool: ...
    def valid(self) -> bool: ...
    def targets_me(self) -> bool: ...

class Loc(_Located):
    id: int
    name: Optional[str]
    shape: int
    angle: int
    layer: int
    changed: bool
    def interact(self, action: Action) -> bool: ...
    def interact_via(self, points: Sequence[Point], action: Action) -> bool: ...
    def valid(self) -> bool: ...

class GroundItem(_Located):
    id: int
    name: Optional[str]
    count: int
    def interact(self, action: Action) -> bool: ...
    def valid(self) -> bool: ...

class InvItem:
    id: int
    name: Optional[str]
    count: int
    slot: int
    com: int
    noted: bool
    def actions(self) -> list[str]: ...
    def interact(self, action: Action) -> bool: ...
    def move_to(self, slot: int) -> bool: ...
    def use_on(self, target: Union["InvItem", Npc, Player, Loc, GroundItem]) -> bool: ...

E = TypeVar('E')

class EntityQuery(Generic[E]):
    def name(self, *names: Union[str, Sequence[str]]) -> "EntityQuery[E]": ...
    def id(self, *ids: Union[int, Sequence[int]]) -> "EntityQuery[E]": ...
    def action(self, action: str) -> "EntityQuery[E]": ...
    def within(self, dist: int) -> "EntityQuery[E]": ...
    def within_of(self, origin: Any, dist: int) -> "EntityQuery[E]": ...
    def inside(self, area: Any) -> "EntityQuery[E]": ...
    def layer(self, layer: int) -> "EntityQuery[E]": ...
    def reachable(self) -> "EntityQuery[E]": ...
    def where(self, predicate: Callable[[E], bool]) -> "EntityQuery[E]": ...
    def results(self) -> list[E]: ...
    def nearest(self) -> Optional[E]: ...
    def nearest_prefer_local(self, prefer_radius: int) -> Optional[E]: ...
    def first(self) -> Optional[E]: ...
    def exists(self) -> bool: ...
    def count(self) -> int: ...

class _Npcs:
    def query(self) -> EntityQuery[Npc]: ...
    def all(self) -> list[Npc]: ...
    def get(self, index: int) -> Optional[Npc]: ...
    def nearest(self, count: int = 1) -> list[Npc]: ...

class _Players:
    def query(self) -> EntityQuery[Player]: ...
    def all(self) -> list[Player]: ...
    def local(self) -> Player: ...

class _Locs:
    def query(self) -> EntityQuery[Loc]: ...
    def at(self, tile: Any, layer: Optional[int] = None) -> Optional[Loc]: ...

class _GroundItems:
    def query(self) -> EntityQuery[GroundItem]: ...

npcs: _Npcs
players: _Players
locs: _Locs
ground_items: _GroundItems

class NpcType:
    id: int
    name: Optional[str]
    examine: Optional[str]
    ops: list[Optional[str]]
    size: int
    combat_level: Optional[int]

class ItemType:
    id: int
    name: Optional[str]
    examine: Optional[str]
    ops: list[Optional[str]]
    inventory_ops: list[Optional[str]]
    stackable: bool
    members: bool
    value: int
    note_of: Optional[int]

class LocType:
    id: int
    name: Optional[str]
    examine: Optional[str]
    ops: list[Optional[str]]
    width: int
    length: int
    blocks_walk: bool
    blocks_projectiles: bool

# Settings

class SettingDef:
    """One setting of a schema. type is 'boolean', 'number', 'string', 'string[]' or 'tile'."""
    def __init__(self, type: str = ..., default: Any = None, label: Optional[str] = None, min: Optional[float] = None,
                 max: Optional[float] = None, help: Optional[str] = None, options: Optional[list[str]] = None,
                 option_labels: Optional[dict[str, str]] = None, group: Optional[str] = None) -> None: ...

class SettingsBag:
    def __getattr__(self, name: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def __contains__(self, key: str) -> bool: ...
    def bool(self, key: str, fallback: bool = False) -> bool: ...
    def num(self, key: str, fallback: float = 0) -> float: ...
    def str(self, key: str, fallback: str = '') -> str: ...
    def list(self, key: str, fallback: Optional[list[str]] = None) -> list[str]: ...
    def tile(self, key: str, fallback: "Tile") -> "Tile": ...
    def raw(self) -> dict[str, Any]: ...

# Geometry

class Tile:
    x: int
    z: int
    level: int
    def __init__(self, x: int, z: int, level: int = 0) -> None: ...
    @staticmethod
    def from_tile(tile: Any) -> "Tile": ...
    def distance_to(self, other: Any) -> int: ...
    def translate(self, dx: int, dz: int) -> "Tile": ...
    def equals(self, other: Any) -> bool: ...

class Area:
    @staticmethod
    def rectangular(a: Any, b: Any) -> "Area": ...
    @staticmethod
    def circular(center: Any, radius: int) -> "Area": ...
    @staticmethod
    def polygon(points: Sequence[Point], level: int = 0) -> "Area": ...
    def contains(self, tile: Any) -> bool: ...
    def get_random_tile(self) -> Tile: ...

# Events

class Event:
    """The payload of tick, chat_message, skill_xp, skill_level, inventory_changed, varp_changed and
    script_finish, with one attribute per field."""
    def __getattr__(self, name: str) -> Any: ...

class _EventBus:
    def on(self, event: str, callback: Callable[..., Any]) -> Callable[[], None]: ...
    def off(self, event: str, callback: Callable[..., Any]) -> None: ...

events: _EventBus

# Waiting

class _Execution:
    def delay(self, ms: int) -> Wait[None]: ...
    def delay_ticks(self, n: int) -> Wait[None]: ...
    def delay_until(self, cond: Callable[[], bool], timeout_ms: int = 6000) -> Wait[bool]: ...
    def delay_until_ticks(self, cond: Callable[[], bool], max_ticks: int) -> Wait[bool]: ...
    def note_progress(self) -> None: ...

execution: _Execution

# Bots

class AbstractBot:
    loop_delay: int
    loop_cadence: Optional[dict[str, Any]]
    settings: SettingsBag
    def log(self, *args: Any) -> None: ...
    def on(self, event: str, callback: Callable[..., Any]) -> None: ...
    def request_finish(self, reason: str) -> None: ...
    def grind_targets(self) -> list[str]: ...
    def ignored_randoms(self) -> list[str]: ...
    def lamp_skill(self) -> str: ...

class LoopingBot(AbstractBot):
    def loop(self) -> Union[int, None, Wait[Optional[int]]]: ...

class Task:
    label: Optional[str]
    def __init__(self, validate: Optional[Callable[[], Any]] = None, execute: Optional[Callable[[], Any]] = None, label: Optional[str] = None) -> None: ...
    def validate(self) -> Any: ...
    def execute(self) -> Any: ...

class TaskBot(LoopingBot):
    active_task_name: Optional[str]
    def add(self, *tasks: Any) -> None: ...

class BranchTask:
    def validate(self) -> bool: ...
    def success(self) -> Union["BranchTask", "LeafTask"]: ...
    def failure(self) -> Union["BranchTask", "LeafTask"]: ...

class LeafTask:
    def execute(self) -> Any: ...

class TreeBot(LoopingBot):
    def root(self) -> Union[BranchTask, LeafTask]: ...

class BotManifest:
    name: str
    create: Callable[[], AbstractBot]
    settings_schema: Optional[dict[str, SettingDef]]

def define_bot(name: str = ..., create: Callable[[], AbstractBot] = ..., description: Optional[str] = None,
               version: Optional[str] = None, category: Optional[str] = None, tags: Optional[list[str]] = None,
               settings_schema: Optional[dict[str, SettingDef]] = None) -> BotManifest: ...
def resolve_loop_cadence(loop_delay_ms: int, override: Optional[dict[str, Any]] = None) -> dict[str, Any]: ...

# Items

class _Inventory:
    def items(self) -> list[InvItem]: ...
    def first(self, name: str) -> Optional[InvItem]: ...
    def contains(self, name: str) -> bool: ...
    def count(self, name: str) -> int: ...
    def count_by_id(self, id: int) -> int: ...
    def used(self) -> int: ...
    def free(self) -> int: ...
    def is_full(self) -> bool: ...

class _Equipment:
    def items(self) -> list[InvItem]: ...
    def contains(self, name: str) -> bool: ...
    def equip(self, name: str) -> Wait[bool]: ...
    def unequip(self, name: str) -> Wait[bool]: ...

inventory: _Inventory
equipment: _Equipment

# You and the game

class _Game:
    def ingame(self) -> bool: ...
    def tile(self) -> Optional[Tile]: ...
    def energy(self) -> int: ...
    def run_enabled(self) -> bool: ...
    def set_run(self, on: bool) -> None: ...
    def weight(self) -> int: ...
    def in_combat(self) -> bool: ...
    def animating(self) -> bool: ...
    def moving(self) -> bool: ...
    def tick(self) -> int: ...
    def my_name(self) -> Optional[str]: ...
    def combat_level(self) -> int: ...
    def combat_mode(self) -> int: ...
    def combat_styles(self) -> Optional[list[tuple[int, str]]]: ...
    def combat_style_resolution(self, style: str) -> Optional[CombatStyleResolution]: ...
    def combat_style_mode(self, style: str) -> Optional[int]: ...
    def has_combat_style(self, style: str) -> bool: ...
    def set_combat_style(self, style: Union[str, int]) -> bool: ...
    def set_combat_mode(self, mode: int) -> bool: ...
    def auto_retaliate_on(self) -> bool: ...
    def set_auto_retaliate(self, on: bool) -> bool: ...
    def attacked_by_player(self) -> bool: ...
    def cast_on_npc(self, spell: str, npc: Npc) -> bool: ...
    def cast_on_player(self, spell: str, player: Player) -> bool: ...
    def cast_on_loc(self, spell: str, loc: Loc) -> bool: ...
    def cast_on_ground_item(self, spell: str, item: GroundItem) -> bool: ...
    def cast_on_item(self, spell: str, item: InvItem) -> bool: ...
    def teleport(self, name: str) -> bool: ...

class _Skills:
    def index(self, name: str) -> int: ...
    def level(self, name: str) -> int: ...
    def effective(self, name: str) -> int: ...
    def xp(self, name: str) -> int: ...
    def hp_fraction(self) -> float: ...

class _Reader:
    def varp(self, id: int) -> int: ...
    def pid(self) -> int: ...
    def main_modal(self) -> int: ...
    def side_modal(self) -> int: ...
    def chat_modal(self) -> int: ...
    def interface_open(self, id: int) -> bool: ...
    def component_text(self, com: int) -> Optional[str]: ...
    def count_dialog_open(self) -> bool: ...
    def inventory(self, com: int) -> list[InvItem]: ...
    def npc_type(self, id: int) -> Optional[NpcType]: ...
    def item_type(self, id: int) -> Optional[ItemType]: ...
    def loc_type(self, id: int) -> Optional[LocType]: ...

class _Chat:
    def say(self, text: str) -> None: ...
    def send_pm(self, name: str, text: str) -> None: ...
    def command(self, text: str) -> None: ...

class _Friends:
    def list(self) -> list[tuple[str, int]]: ...
    def add(self, name: str) -> None: ...
    def remove(self, name: str) -> None: ...

class _Ignores:
    def list(self) -> list[str]: ...
    def add(self, name: str) -> None: ...
    def remove(self, name: str) -> None: ...

class _DirectNavigator:
    def walk(self, dest: Any, run: bool = False) -> bool: ...
    def walk_to(self, dest: Any, radius: int = 2, timeout_ms: int = 45000, run: bool = False) -> Wait[bool]: ...
    def walk_path(self, points: Sequence[Point], run: bool = False) -> None: ...
    def reachable(self, dest: Any) -> bool: ...
    def path(self, dest: Any) -> Optional[list[Tile]]: ...
    def destination(self) -> Optional[Tile]: ...

game: _Game
skills: _Skills
reader: _Reader
chat: _Chat
friends: _Friends
ignores: _Ignores
direct_navigator: _DirectNavigator

# Interfaces

class Component:
    id: int
    root: int
    layer: Optional[int]
    type: str
    button: Optional[str]
    button_text: Optional[str]
    text: str
    colour: int
    hidden: bool
    visible: bool
    options: Optional[list[Optional[str]]]
    target_verb: Optional[str]
    target_name: Optional[str]
    x: int
    y: int
    width: int
    height: int
    children: list[int]
    item: Optional[int]
    varp: Optional[int]
    value: Optional[int]
    def click(self) -> bool: ...

class _Interfaces:
    def component(self, id: int) -> Optional[Component]: ...
    def root(self, id: int) -> list[Component]: ...
    def open(self) -> list[int]: ...
    def tab(self, n: int) -> int: ...
    def find(self, text: Optional[str] = None, button: Optional[str] = None, root: Optional[int] = None) -> list[Component]: ...
    def click(self, id: int) -> bool: ...
    def click_text(self, text: str, root: Optional[int] = None) -> bool: ...

interfaces: _Interfaces

# Random events

class _RandomEvent:
    kind: str
    name: str
    tile: Optional[Tile]
    def key(self) -> str: ...

class _RandomEvents:
    handling: bool
    def detect(self) -> Optional[_RandomEvent]: ...
    def handle(self, event: _RandomEvent, log: Optional[Callable[[str], None]] = None) -> Wait[bool]: ...

random_events: _RandomEvents

# Walking across the world

class _Traversal:
    remaining: int
    last_outcome: Optional[str]
    last_reason: Optional[str]
    def teleports_enabled(self) -> bool: ...
    def request_repath(self, reason: Optional[str] = None) -> None: ...
    def walk_to(self, dest: Tile, radius: int = 2, timeout_ms: Optional[int] = None, max_expansions: Optional[int] = None, use_teleport_catalog: Optional[bool] = None, policy: Optional[dict[str, Any]] = None, bank_item_counts: Optional[dict[str, int]] = None, avoid_zones: Optional[list[Any]] = None, log: Optional[Callable[[str], None]] = None, force_repath: bool = False) -> Wait[bool]: ...
    def walk_resilient(self, dest: Tile, radius: int = 2, attempts: Optional[int] = None, timeout_ms: Optional[int] = None, scene_radius: Optional[int] = None, max_budget: Optional[int] = None, use_teleport_catalog: Optional[bool] = None, policy: Optional[dict[str, Any]] = None, bank_item_counts: Optional[dict[str, int]] = None, avoid_zones: Optional[list[Any]] = None, log: Optional[Callable[[str], None]] = None) -> Wait[bool]: ...
    def try_nearby_door(self, log: Optional[Callable[[str], None]] = None) -> Wait[bool]: ...

traversal: _Traversal
NAV_PURE_WALK: dict[str, Any]
NAV_WITH_TELES: dict[str, Any]
def world_state() -> dict[str, Any]: ...
def bank_locations() -> list[dict[str, Any]]: ...
def bank_unlocked(bank: dict[str, Any], settings: Optional[dict[str, bool]] = None) -> bool: ...
def nearest_banks(tile: Tile, settings: Optional[dict[str, bool]] = None) -> list[dict[str, Any]]: ...
def nearest_bank(tile: Tile, settings: Optional[dict[str, bool]] = None) -> Optional[dict[str, Any]]: ...
def nearest_reachable_bank(tile: Tile, candidates: int = 4, settings: Optional[dict[str, bool]] = None) -> Optional[dict[str, Any]]: ...
def pick_choice(options: Sequence[str], choose: Sequence[str]) -> Optional[str]: ...
def special_crossing_for_transport(transport: dict[str, Any], approach: Tile, step: Tile) -> Optional[dict[str, Any]]: ...

# Reach

class GameMessage:
    seq: int
    text: str

Pattern = Union[str, Callable[[str], bool]]

class _GameMessages:
    def mark(self) -> int: ...
    def since(self, mark: int) -> list[GameMessage]: ...
    def saw_since(self, mark: int, pattern: Pattern) -> bool: ...
    def first_since(self, mark: int, pattern: Pattern) -> Optional[GameMessage]: ...
    def recent(self, limit: int = 8) -> list[GameMessage]: ...

game_messages: _GameMessages
CANT_REACH: str
def WRONG_SIDE(text: str) -> bool: ...

class _Reach:
    def entity_op(self, find: Callable[[], Any], op: str, expect: Callable[[], bool], open_when_unreachable: bool = False, expect_ms: int = 5000, what: Optional[str] = None, log: Optional[Callable[[str], None]] = None) -> Wait[str]: ...
    def loc_op(self, name: str, op: str, near: Tile, expect: Callable[[], bool], within: int = 10, id: Optional[int] = None, expect_ms: int = 12000, refused: Optional[Pattern] = None, log: Optional[Callable[[str], None]] = None) -> Wait[str]: ...
    def npc_dialog(self, name: str, near: Tile, open_ms: int = 15000, log: Optional[Callable[[str], None]] = None) -> Wait[str]: ...

reach: _Reach
def is_openable_barrier(name: Optional[str], actions: Sequence[Optional[str]]) -> bool: ...
def is_open_barrier_leaf(name: Optional[str], actions: Sequence[Optional[str]]) -> bool: ...
def open_op(actions: Sequence[str]) -> Optional[str]: ...
def close_op(actions: Sequence[str]) -> Optional[str]: ...
def talk_op(actions: Sequence[str]) -> Optional[str]: ...
def toward_dest(door: Tile, here: Tile, dest: Tile) -> bool: ...

# Dialogues and make menus

MAKE_X: int
MAKE_ALL: int

class MakeProduct:
    name: str
    item: Optional[int]
    item_name: Optional[str]
    amounts: list[int]
    def button(self, amount: int) -> Optional[int]: ...
    def largest(self) -> Optional[int]: ...

class _ChatDialog:
    def is_open(self) -> bool: ...
    def can_continue(self) -> bool: ...
    def continue_(self) -> Wait[bool]: ...
    def options(self) -> list[str]: ...
    def choose_option(self, text: Optional[str] = None) -> Wait[bool]: ...
    def texts(self) -> list[str]: ...
    def products(self) -> list[MakeProduct]: ...
    def is_make_menu(self) -> bool: ...
    def make_products(self) -> list[str]: ...
    def make(self, name: Optional[str] = None) -> Wait[bool]: ...
    def make_one(self, name: Optional[str] = None) -> Wait[bool]: ...
    def make_x(self, name: str, count: int) -> Wait[bool]: ...
    def is_main_make_panel(self) -> bool: ...
    def main_make_products(self) -> list[Optional[str]]: ...
    def make_from_panel(self, name: str, op: Optional[str] = None) -> Wait[bool]: ...
    def make_from_panel_max(self, name: str) -> Wait[bool]: ...

class _Modals:
    def main(self) -> int: ...
    def is_open(self) -> bool: ...
    def close(self) -> Wait[bool]: ...
    def close_if_open(self) -> Wait[None]: ...

chat_dialog: _ChatDialog
modals: _Modals

# The bank

class _Bank:
    def root(self) -> int: ...
    def is_open(self) -> bool: ...
    def ready(self) -> bool: ...
    def wait_ready(self, timeout_ms: int = 4000) -> Wait[bool]: ...
    def set_note_mode(self, on: bool) -> Wait[bool]: ...
    def items(self) -> list[InvItem]: ...
    def side_items(self) -> list[InvItem]: ...
    def count(self, name: str) -> int: ...
    def count_by_id(self, id: int) -> int: ...
    def withdraw(self, name: str, op: str = 'Withdraw 1') -> bool: ...
    def withdraw_by_id(self, id: int, op: str = 'Withdraw 1') -> bool: ...
    def withdraw_x(self, name: str, count: int) -> Wait[bool]: ...
    def withdraw_x_by_id(self, id: int, count: int, lands_as_id: Optional[int] = None) -> Wait[bool]: ...
    def withdraw_load(self, name: str) -> Wait[bool]: ...
    def deposit(self, name: str, op: str = 'Deposit 1') -> bool: ...
    def deposit_inventory(self) -> Wait[None]: ...
    def deposit_all_matching(self, matches: Callable[[str, int], bool]) -> Wait[None]: ...
    def open_booth(self, stand: Tile, booth_name: str = 'Bank booth', op: str = 'Use-quickly') -> Wait[bool]: ...
    def open_nearest(self, booth_name: str = 'Bank booth', op: str = 'Use-quickly') -> Wait[bool]: ...
    def open_nearest_access(self, access: dict[str, Any]) -> Wait[bool]: ...
    def open_npc_access(self, access: dict[str, Any]) -> Wait[bool]: ...
    def close(self, timeout_ms: int = 3000) -> Wait[bool]: ...

class _Banking:
    def open(self, stand: Optional[Tile] = None, booth_name: str = 'Bank booth', booth_op: str = 'Use-quickly', obstacles: Optional[list[str]] = None, destination: Any = None, prefer_nearby: bool = True, nearby_radius: int = 14) -> Wait[bool]: ...
    def bank_nearest(self, deposit: Callable[[str], bool], common_junk: bool = True, destination: Any = None, return_to: Optional[Tile] = None, booth_name: str = 'Bank booth', booth_op: str = 'Use-quickly', after_deposit: Optional[Callable[[], Any]] = None) -> Wait[bool]: ...

bank: _Bank
banking: _Banking

# Shops and trades

class _Shop:
    def stock_com(self) -> int: ...
    def side_com(self) -> int: ...
    def is_open(self) -> bool: ...
    def open(self, npc_name: str) -> Wait[bool]: ...
    def stock(self) -> list[InvItem]: ...
    def buy(self, name: str, n: int) -> Wait[int]: ...
    def buy_by_id(self, id: int, n: int) -> Wait[int]: ...
    def sell(self, name: str, n: int, pick: Optional[Callable[[InvItem], bool]] = None) -> Wait[int]: ...
    def sell_all(self, name: str, pick: Optional[Callable[[InvItem], bool]] = None) -> Wait[int]: ...
    def close(self) -> Wait[bool]: ...

class _Trade:
    def on_offer_screen(self) -> bool: ...
    def on_confirm_screen(self) -> bool: ...
    def active(self) -> bool: ...
    def partner(self) -> Optional[str]: ...
    def status(self) -> list[str]: ...
    def their_accepted(self) -> bool: ...
    def waiting(self) -> bool: ...
    def my_offer(self) -> list[InvItem]: ...
    def their_offer(self) -> list[InvItem]: ...
    def request(self, player_name: str) -> bool: ...
    def offer_all(self, item_name: str, pick: Optional[Callable[[InvItem], bool]] = None) -> bool: ...
    def offer(self, item_name: str, n: int, pick: Optional[Callable[[InvItem], bool]] = None) -> Wait[bool]: ...
    def remove_all(self) -> Wait[bool]: ...
    def accept(self) -> bool: ...
    def decline(self) -> Wait[bool]: ...

shop: _Shop
trade: _Trade
SELL_STACK_STEP: int
def shop_op_batch(ops: Sequence[Optional[str]], verb: str, remaining: int) -> list[int]: ...
def parse_trade_partner_header(header: Optional[str]) -> Optional[str]: ...
COMMON_BANK_LOOT: list[str]
RANDOM_EVENT_CASKET_ID: int
PERIODIC_BANK_SETTINGS: dict[str, SettingDef]
NEARBY_BANK_RADIUS: int
def withdraw_op(ops: Sequence[Optional[str]], amount: str) -> Optional[str]: ...
def deposit_all_except(keep: Sequence[str]) -> Callable[..., bool]: ...
def deposit_matcher(own: Callable[[str], bool], include_common: bool) -> Callable[..., bool]: ...
def matches_common_bank_loot(name: str, id: int = -1) -> bool: ...
def is_disposable_gather_junk(name: Optional[str], id: int = -1) -> bool: ...
def parse_bank_strategy(label: str) -> str: ...
def should_bank_now(strategy: str, state: Any) -> bool: ...

class PeriodicBank(Task):
    def __init__(self, strategy: Callable[[], str], items_threshold: Callable[[], int], minutes_threshold: Callable[[], int], count_loot: Callable[[], int], deposit: Callable[[str], bool], after_deposit: Optional[Callable[[], Any]] = None, common_junk: Optional[Callable[[], bool]] = None, return_to: Optional[Callable[[], Optional[Tile]]] = None, log: Optional[Callable[[str], None]] = None) -> None: ...

# Control

def log(*args: Any) -> None: ...
def debug(*args: Any) -> None: ...
def stop_script() -> None: ...
def stop_account() -> None: ...
def send_bot_message(username: str, message: Any) -> bool: ...

# The side tabs

class Quest:
    name: str
    status: str
    com: int

class _Quests:
    def all(self) -> list[Quest]: ...
    def status(self, name: str) -> str: ...
    def points(self) -> int: ...
    def journal(self, name: str) -> Wait[list[str]]: ...

class _Prayer:
    def points(self) -> int: ...
    def max(self) -> int: ...
    def full(self) -> bool: ...
    def known(self, name: str) -> bool: ...
    def available(self, name: str) -> bool: ...
    def active(self, name: str) -> bool: ...
    def set(self, name: str, on: bool) -> Wait[bool]: ...
    def clear(self) -> Wait[None]: ...

class _Special:
    def energy(self) -> int: ...
    def armed(self) -> bool: ...
    def wielded(self) -> str: ...
    def cost(self, weapon_name: str) -> Optional[int]: ...
    def ready(self, weapon_name: str) -> bool: ...
    def bar_component(self) -> int: ...
    def arm(self) -> Wait[bool]: ...

class _Autocast:
    def armed(self) -> bool: ...
    def staff_tab_attached(self) -> bool: ...
    def arm(self, spell: str, log: Optional[Callable[[str], None]] = None) -> Wait[bool]: ...

class CombatStyleResolution:
    requested: str
    effective: str
    mode: int

quests: _Quests
prayer: _Prayer
special: _Special
autocast: _Autocast
PRAYER_NAMES: list[str]
AUTOCAST_SPELLS: list[str]
COMBAT_STYLE_OPTIONS: list[str]
RANGE_STYLE_OPTIONS: list[str]
SA_MAX_ENERGY: int
def parse_combat_style(name: str) -> str: ...
def try_parse_combat_style(name: str) -> Optional[str]: ...
def parse_interface_combat_style(label: str) -> Optional[str]: ...
def resolve_combat_style(style: str, offered: Sequence[tuple[int, str]]) -> Optional[CombatStyleResolution]: ...
def parse_range_style(name: str) -> int: ...
