# Declarations of what the client adds to every script's builtins, for editors only: Pylance and Pyright
# read this file, the client never does. See docs/ScriptingApi.md for what each function does.

from typing import Any, Optional, Sequence, Union

Ids = Union[int, Sequence[int], None]
Point = tuple[int, int]

settings: "Settings"

COMBAT_TICKS: int
INVENTORY: int
EQUIPMENT: int
BANK: int
BANK_INVENTORY: int
INVENTORY_SIZE: int
ATTACK: int
DEFENCE: int
STRENGTH: int
HITPOINTS: int
RANGED: int
PRAYER: int
MAGIC: int
COOKING: int
WOODCUTTING: int
FLETCHING: int
FISHING: int
FIREMAKING: int
CRAFTING: int
SMITHING: int
MINING: int
HERBLORE: int
AGILITY: int
THIEVING: int
RUNECRAFT: int
LAYER_WALL: int
LAYER_WALL_DECOR: int
LAYER_GROUND: int
LAYER_GROUND_DECOR: int

class _Entity:
    index: int
    x: int
    z: int
    level: int
    animation: int
    moving: bool
    hp: Optional[int]
    max_hp: Optional[int]
    last_hit_tick: Optional[int]
    target: Optional[tuple[str, int]]
    def is_moving(self) -> bool: ...
    def in_combat(self) -> bool: ...

class Npc(_Entity):
    id: int

class Player(_Entity):
    name: Optional[str]
    combat_level: int

class GroundItem:
    id: int
    count: int
    x: int
    z: int
    level: int

class Loc:
    id: int
    x: int
    z: int
    level: int
    shape: int
    angle: int
    layer: int

class Item:
    id: int
    count: int
    slot: int
    com: int

class Settings:
    def __getattr__(self, name: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def __contains__(self, key: str) -> bool: ...

def log(*args: Any) -> None: ...
def debug(*args: Any) -> None: ...
def get_tick() -> int: ...
def stop_script() -> None: ...
def stop_account() -> None: ...
def send_bot_message(username: str, message: Any) -> bool: ...

def get_x() -> int: ...
def get_z() -> int: ...
def get_level() -> int: ...
def get_position() -> Point: ...
def get_pid() -> int: ...
def get_name() -> Optional[str]: ...
def get_combat_level() -> int: ...
def get_run_energy() -> int: ...
def get_weight() -> int: ...
def is_moving() -> bool: ...
def get_walk_destination() -> Optional[Point]: ...
def in_combat() -> bool: ...
def is_running() -> bool: ...
def get_local_player() -> Player: ...

def get_current_stat(stat: int) -> int: ...
def get_max_stat(stat: int) -> int: ...
def get_experience(stat: int) -> int: ...
def get_hp() -> int: ...
def get_max_hp() -> int: ...
def get_hp_percent() -> int: ...

def distance_to(x: int, z: int) -> int: ...
def distance(x1: int, z1: int, x2: int, z2: int) -> int: ...
def in_radius_of(x: int, z: int, radius: int) -> bool: ...
def in_rect(x: int, z: int, width: int, height: int) -> bool: ...
def at(x: int, z: int) -> bool: ...

def get_npcs(ids: Ids = None, radius: Optional[int] = None) -> list[Npc]: ...
def get_nearest_npc_by_id(ids: Ids = None, radius: Optional[int] = None, in_combat: Optional[bool] = None) -> Optional[Npc]: ...
def get_npc(index: int) -> Optional[Npc]: ...
def get_players(radius: Optional[int] = None) -> list[Player]: ...
def get_player_by_name(name: str) -> Optional[Player]: ...
def get_ground_items(ids: Ids = None, radius: Optional[int] = None) -> list[GroundItem]: ...
def get_nearest_ground_item_by_id(ids: Ids = None, radius: Optional[int] = None) -> Optional[GroundItem]: ...
def get_loc_at(x: int, z: int, layer: Optional[int] = None) -> Optional[Loc]: ...

def get_inventory(com: int = 3214) -> list[Item]: ...
def get_equipment() -> list[Item]: ...
def get_inventory_count_by_id(ids: Ids = None, com: int = 3214) -> int: ...
def get_inventory_item_by_id(ids: Ids = None, com: int = 3214) -> Optional[Item]: ...
def get_empty_slots() -> int: ...
def is_inventory_full() -> bool: ...

def get_main_modal() -> int: ...
def get_side_modal() -> int: ...
def get_chat_modal() -> int: ...
def is_interface_open(id: int) -> bool: ...
def get_component_text(com: int) -> Optional[str]: ...
def is_count_dialog_open() -> bool: ...
def get_varp(id: int) -> int: ...
def get_friends() -> list[tuple[str, int]]: ...
def get_ignores() -> list[str]: ...

def walk_to(x: int, z: int, run: bool = False) -> None: ...
def walk_path(points: Sequence[Point], run: bool = False) -> None: ...
def interact_npc(npc: Union[Npc, int], op: int) -> bool: ...
def talk_to_npc(npc: Union[Npc, int]) -> bool: ...
def attack_npc(npc: Union[Npc, int]) -> bool: ...
def interact_player(player: Union[Player, int], op: int) -> bool: ...
def interact_loc(id: int, x: int, z: int, op: int) -> None: ...
def interact_loc_via(points: Sequence[Point], id: int, x: int, z: int, op: int) -> None: ...
def interact_ground_item(item: GroundItem, op: int) -> bool: ...
def take_ground_item(item: GroundItem) -> bool: ...

def item_op(item: Item, op: int) -> bool: ...
def inv_button(item: Item, op: int) -> bool: ...
def drop_item(item: Item) -> bool: ...
def move_item(com: int, from_slot: int, to_slot: int) -> None: ...
def use_item_on_npc(item: Item, npc: Union[Npc, int]) -> bool: ...
def use_item_on_player(item: Item, player: Union[Player, int]) -> bool: ...
def use_item_on_loc(item: Item, id: int, x: int, z: int) -> bool: ...
def use_item_on_ground_item(item: Item, ground_item: GroundItem) -> bool: ...
def use_item_on_item(item: Item, target: Item) -> bool: ...

def cast_on_npc(spell: int, npc: Union[Npc, int]) -> bool: ...
def cast_on_player(spell: int, player: Union[Player, int]) -> bool: ...
def cast_on_loc(spell: int, id: int, x: int, z: int) -> None: ...
def cast_on_ground_item(spell: int, ground_item: GroundItem) -> bool: ...
def cast_on_item(spell: int, item: Item) -> bool: ...

def click_button(com: int) -> None: ...
def continue_dialogue() -> None: ...
def answer_count(value: int) -> None: ...
def close_interfaces() -> None: ...
def set_run(run: bool) -> None: ...

def say(text: str) -> None: ...
def send_pm(name: str, text: str) -> None: ...
def command(text: str) -> None: ...
def add_friend(name: str) -> None: ...
def remove_friend(name: str) -> None: ...
def add_ignore(name: str) -> None: ...
def remove_ignore(name: str) -> None: ...
