"""rs2b0t's world catalogs as data, generated by tools/catalogs/export_rs2b0t.ts from rs2b0t (MIT, see
third_party/rs2b0t). Don't edit it by hand: change rs2b0t's tables and run the exporter again."""

from rs2004.geometry import Tile

FISHING_LOCATIONS = [
    {"name": "Draynor Village", "spot": Tile(3086, 3231, 0), "bank_stand": Tile(3093, 3243, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["shrimp", "anchovies", "sardine", "herring"], "range_stand": Tile(3100, 3257, 0), "range_name": "Fireplace", "obstacles": ["door", "gate"], "notes": "cook: Draynor house fireplace"},
    {"name": "Catherby", "spot": Tile(2845, 3431, 0), "bank_stand": Tile(2809, 3441, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "camp_radius": 80, "chase_radius": 28, "sweep": [Tile(2845, 3431, 0), Tile(2855, 3428, 0)], "verified": True, "resources": ["mackerel", "cod", "bass", "tuna", "lobster", "swordfish", "shark"], "obstacles": ["door", "gate"], "range_stand": Tile(2817, 3443, 0), "range_name": "Range", "notes": "cook: Catherby range (bank house)"},
    {
        "name": "Fishing Guild",
        "spot": Tile(2604, 3420, 0),
        "bank_stand": Tile(2586, 3420, 0),
        "booth_name": "Bank booth",
        "booth_op": "Use-quickly",
        "camp_radius": 80,
        "chase_radius": 28,
        "verified": True,
        "resources": ["mackerel", "cod", "bass", "tuna", "lobster", "swordfish", "shark"],
        "bait_vendor": {"keeper": "Roachey", "stand": Tile(2596, 3399, 0), "price": 2, "item": "Feather"},
        "notes": "Bank requires Fishing 68; cook: Ardougne range S of guild",
        "range_stand": Tile(2616, 3395, 0),
        "range_name": "Range",
        "obstacles": ["door", "gate"],
    },
    {"name": "Barbarian Village", "spot": Tile(3104, 3430, 0), "bank_stand": Tile(3094, 3493, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "camp_radius": 72, "chase_radius": 28, "verified": True, "resources": ["trout", "salmon", "pike"], "notes": "Fly/bait river; cook: Barb outdoor fires", "range_stand": Tile(3079, 3444, 0), "range_name": "Fire", "obstacles": ["door", "gate"]},
    {"name": "Seers (fly fishing)", "spot": Tile(2716, 3532, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "camp_radius": 80, "chase_radius": 28, "verified": True, "resources": ["trout", "salmon", "pike"], "obstacles": ["door", "gate"], "notes": "River north of Seers toward Rellekka; shore stand; cook: Sinclair mansion range (Large-door approach)", "range_stand": Tile(2735, 3581, 0), "range_name": "Range"},
    {"name": "Karamja (Musa Point)", "spot": Tile(2924, 3178, 0), "bank_stand": Tile(3093, 3243, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "camp_radius": 72, "chase_radius": 28, "verified": True, "resources": ["tuna", "lobster", "swordfish"], "notes": "No local bank — deposit via ship to Draynor / Port Sarim area"},
    {"name": "Taverley Dungeon (lava eels)", "spot": Tile(2884, 9767, 0), "bank_stand": Tile(2946, 3369, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["lava eel"], "notes": "Dungeon spot; surface bank at Falador West"},
    {"name": "Gnome Stronghold (fishing)", "spot": Tile(2388, 3420, 0), "bank_stand": Tile(2449, 3482, 1), "booth_name": "Bank booth", "booth_op": "Use-quickly", "camp_radius": 72, "chase_radius": 28, "verified": False, "resources": ["trout", "salmon"], "notes": "Tick manip: Tannerfishing (fly + cook/eat). Unverified seed; bank Grand Tree 1F"},
    {
        "name": "Shilo Village",
        "spot": Tile(2841, 2970, 0),
        "bank_stand": Tile(2852, 2954, 0),
        "camp_radius": 48,
        "chase_radius": 28,
        "verified": False,
        "resources": ["trout", "salmon"],
        "sweep": [Tile(2862, 2971, 0), Tile(2856, 2972, 0), Tile(2841, 2970, 0), Tile(2836, 2970, 0), Tile(2822, 2968, 0), Tile(2832, 2973, 0), Tile(2834, 2975, 0), Tile(2850, 2977, 0), Tile(2855, 2978, 0), Tile(2860, 2977, 0), Tile(2869, 2978, 0)],
        "bait_vendor": {"keeper": "Fernahei", "stand": Tile(2870, 2971, 0), "price": 2, "item": "Feather"},
        "notes": "Requires Shilo Village quest; fly only, the teller banks and Fernahei sells the feathers.",
    },
]

SHILO_WATER_VENDOR = {"keeper": "Obli", "stand": Tile(2825, 2959, 0), "item": "Vial of water"}

WOODCUTTING_LOCATIONS = [
    {"name": "Draynor (trees)", "spot": Tile(3098, 3242, 0), "bank_stand": Tile(3093, 3243, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["logs"], "notes": "Normal trees near Draynor bank"},
    {"name": "Draynor Oaks", "spot": Tile(3105, 3245, 0), "bank_stand": Tile(3093, 3243, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["oak"], "notes": "East of Draynor bank"},
    {"name": "Draynor Willows", "spot": Tile(3087, 3234, 0), "bank_stand": Tile(3093, 3243, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["willow"], "notes": "Southwest of Draynor bank"},
    {"name": "Seers (trees)", "spot": Tile(2724, 3474, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["logs"], "notes": "South of Seers bank"},
    {"name": "Seers Oaks", "spot": Tile(2721, 3483, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["oak"], "notes": "Just SW/S of Seers bank door"},
    {"name": "Seers Willows", "spot": Tile(2711, 3500, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["willow"], "notes": "Northwest of Seers bank"},
    {"name": "Seers Maples", "spot": Tile(2728, 3501, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["maple"], "notes": "North of Seers bank"},
    {"name": "Seers Yews (cemetery)", "spot": Tile(2708, 3462, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["yew"], "notes": "Church/cemetery SW of Seers (not party room)"},
    {"name": "Edgeville Yews", "spot": Tile(3087, 3470, 0), "bank_stand": Tile(3094, 3493, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["yew"], "notes": "South of Edgeville bank"},
    {"name": "Sorcerer's Tower", "spot": Tile(2702, 3398, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["magic"], "notes": "Magic trees south of Sorcerer's Tower / far south of Seers"},
    {"name": "Gnome Stronghold", "spot": Tile(2434, 3425, 0), "bank_stand": Tile(2449, 3482, 1), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["magic"], "notes": "Bank is Grand Tree 1F booths (open, no quest gate) — seed stand"},
    {"name": "S Falador Oaks", "spot": Tile(2976, 3290, 0), "bank_stand": Tile(2946, 3369, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": False, "resources": ["oak"], "notes": "Tick manip: 2t retaliate oaks (chickens nearby). Unverified seed."},
    {"name": "Lumbridge Farmer Willows", "spot": Tile(3221, 3290, 0), "bank_stand": Tile(3093, 3243, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": False, "resources": ["willow"], "notes": "Tick manip: 3t farmer willows (6-tick cycle). Unverified seed."},
    {"name": "Lumbridge Castle Willows", "spot": Tile(3233, 3241, 0), "bank_stand": Tile(3093, 3243, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": False, "resources": ["willow"], "notes": "Tick manip: 3t shortbow rapid / retaliate willows. Unverified seed."},
]

ENT_NPC_IDS = [444, 445, 446, 447, 448, 449, 450, 451, 452]

ENT_LIFE_TICKS = 60

MINING_LOCATIONS = [
    {"name": "Al Kharid Mine", "spot": Tile(3299, 3299, 0), "bank_stand": Tile(3269, 3167, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["iron", "silver", "mithril", "adamantite"], "recommended_combat": 29},
    {"name": "Barbarian Village", "spot": Tile(3084, 3417, 0), "bank_stand": Tile(3094, 3493, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["tin", "coal"], "notes": "Tin/coal rocks east of village center"},
    {"name": "Coal Trucks", "spot": Tile(2582, 3481, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["coal"], "notes": "West of Seers; seed spot", "recommended_combat": 55},
    {"name": "Crafting Guild", "spot": Tile(2939, 3282, 0), "bank_stand": Tile(2946, 3369, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["silver", "gold"], "notes": "Requires Crafting 40 + brown apron"},
    {"name": "Desert Mining Camp", "spot": Tile(3323, 9458, 0), "bank_stand": Tile(3308, 3120, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["copper", "tin", "mithril", "adamantite"], "notes": "Underground rocks; requires completed Tourist Trap, camp keys and slave gear", "recommended_combat": 91},
    {"name": "Desert Mining Camp Surface", "spot": Tile(3293, 3016, 0), "bank_stand": Tile(3308, 3120, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["copper", "tin", "iron", "coal"], "notes": "Surface rocks inside the camp; requires completed Tourist Trap and Metal key", "recommended_combat": 91},
    {"name": "Dwarven Mine", "spot": Tile(3021, 9800, 0), "bank_stand": Tile(3013, 3355, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["copper", "tin", "coal", "iron"], "notes": "Underground seed; surface hop ~3019,3449", "recommended_combat": 65},
    {"name": "Edgeville Dungeon Mine", "spot": Tile(3132, 9874, 0), "bank_stand": Tile(3094, 3493, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["copper", "tin", "iron", "coal", "silver", "mithril", "adamantite"], "notes": "Underground; public Edgeville trapdoor route, no Brass key required", "recommended_combat": 85},
    {"name": "Fight Arena Mine", "spot": Tile(2631, 3146, 0), "bank_stand": Tile(2612, 3092, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["iron", "mithril"]},
    {"name": "Grand Tree Mine", "spot": Tile(2465, 9909, 0), "bank_stand": Tile(2449, 3482, 1), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["adamantite"], "notes": "Requires Grand Tree quest; bank is Grand Tree 1F (open, no quest gate)"},
    {"name": "Heroes Guild", "spot": Tile(2930, 9911, 0), "bank_stand": Tile(2725, 3491, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["runite"], "notes": "Requires Heroes' Quest; basement rune rocks east of ladder"},
    {"name": "Lava Maze Runite Mine", "spot": Tile(3058, 3884, 0), "bank_stand": Tile(3094, 3493, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["runite"], "notes": "Wilderness — high risk; bank out at Edgeville", "recommended_combat": 69},
    {"name": "Legends Guild Iron (east)", "spot": Tile(2712, 3330, 0), "bank_stand": Tile(2655, 3283, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": False, "resources": ["iron"], "notes": "Tick manip: iron cadence (3-rock). Unverified seed; bank Ardougne East."},
    {"name": "Legends Guild Iron (west)", "spot": Tile(2694, 3331, 0), "bank_stand": Tile(2655, 3283, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": False, "resources": ["iron"], "notes": "Tick manip: iron cadence (3-rock). Unverified seed; bank Ardougne East."},
    {"name": "Mining Guild", "spot": Tile(3025, 9735, 0), "bank_stand": Tile(3013, 3355, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["iron", "coal", "mithril"], "notes": "Requires Mining 60; underground guild seed"},
    {"name": "North Brimhaven Mine", "spot": Tile(2733, 3224, 0), "bank_stand": Tile(2655, 3283, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["gold"], "notes": "No local bank — ship/path to Ardougne East"},
    {"name": "Rimmington Mine", "spot": Tile(2978, 3247, 0), "bank_stand": Tile(3013, 3355, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["clay", "copper", "tin", "iron"], "notes": "Seed from Doric ore anchors"},
    {"name": "Shilo Village", "spot": Tile(2825, 2997, 0), "bank_stand": Tile(2852, 2954, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["gem rocks"], "notes": "Requires Shilo Village quest; bank gated"},
    {"name": "South-east Ardougne Mine", "spot": Tile(2597, 3233, 0), "bank_stand": Tile(2655, 3283, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": False, "resources": ["iron", "coal"], "notes": "Members; Monastery mine, iron + coal; seed unverified."},
    {"name": "Southeast Varrock Mine", "spot": Tile(3285, 3366, 0), "bank_stand": Tile(3253, 3420, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["clay", "copper", "tin", "iron"]},
    {"name": "Southwest Varrock Mine", "spot": Tile(3181, 3371, 0), "bank_stand": Tile(3185, 3440, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["tin"]},
    {"name": "West Lumbridge Swamp Mine", "spot": Tile(3235, 3163, 0), "bank_stand": Tile(3093, 3243, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["mithril", "adamantite"], "notes": "East swamp rock cluster (west coast unloaded/void on this map)"},
    {"name": "Wilderness Hobgoblin Mine", "spot": Tile(3093, 3751, 0), "bank_stand": Tile(3094, 3493, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["iron", "coal", "mithril", "adamantite"], "notes": "Wilderness — aggressive Hobgoblins; bank out at Edgeville", "recommended_combat": 57},
    {"name": "Wilderness Skeleton Mine", "spot": Tile(3018, 3590, 0), "bank_stand": Tile(3094, 3493, 0), "booth_name": "Bank booth", "booth_op": "Use-quickly", "verified": True, "resources": ["coal"], "notes": "Wilderness — aggressive Skeletons; bank out at Edgeville", "recommended_combat": 45},
]

COW_LOCATIONS = [
    {"name": "Lumbridge cow field", "anchor": Tile(3255, 3288, 0), "uses_al_kharid_toll": True},
    {
        "name": "North-west of Lumbridge",
        "anchor": Tile(3168, 3329, 0),
        "uses_al_kharid_toll": False,
        "bank_destination": {"name": "Draynor", "tile": Tile(3093, 3243, 0)},
    },
    {
        "name": "South of Falador",
        "anchor": Tile(3033, 3306, 0),
        "uses_al_kharid_toll": False,
        "bank_destination": {"name": "Falador East", "tile": Tile(3013, 3355, 0)},
    },
    {
        "name": "East Ardougne cow field",
        "anchor": Tile(2664, 3347, 0),
        "uses_al_kharid_toll": False,
        "bank_destination": {"name": "Ardougne West", "tile": Tile(2616, 3332, 0)},
    },
]

DRAYNOR_BANK = Tile(3093, 3243, 0)

FALADOR_EAST_BANK = Tile(3013, 3355, 0)

ARDOUGNE_WEST_BANK = Tile(2616, 3332, 0)

AL_KHARID_BANK = Tile(3269, 3167, 0)

TOLL_COIN_TARGET = 20

RUNES = {
    "Air rune": {"rune": "Air rune", "talisman": "Air talisman", "level": 1, "bank": "Falador East", "ruins": Tile(2983, 3288, 0)},
    "Mind rune": {"rune": "Mind rune", "talisman": "Mind talisman", "level": 2, "bank": "Edgeville", "ruins": Tile(2980, 3511, 0)},
    "Water rune": {"rune": "Water rune", "talisman": "Water talisman", "level": 5, "bank": "Draynor", "ruins": Tile(3182, 3162, 0)},
    "Earth rune": {"rune": "Earth rune", "talisman": "Earth talisman", "level": 9, "bank": "Varrock East", "ruins": Tile(3303, 3477, 0)},
    "Fire rune": {"rune": "Fire rune", "talisman": "Fire talisman", "level": 14, "bank": "Al Kharid", "ruins": Tile(3310, 3252, 0)},
    "Body rune": {"rune": "Body rune", "talisman": "Body talisman", "level": 20, "bank": "Edgeville", "ruins": Tile(3050, 3442, 0)},
    "Cosmic rune": {"rune": "Cosmic rune", "talisman": "Cosmic talisman", "level": 27, "bank": "Draynor", "ruins": Tile(3173, 9501, 0)},
    "Chaos rune": {"rune": "Chaos rune", "talisman": "Chaos talisman", "level": 35, "bank": "Edgeville", "ruins": Tile(3060, 3585, 0)},
    "Nature rune": {"rune": "Nature rune", "talisman": "Nature talisman", "level": 44, "bank": "Draynor", "ruins": Tile(2865, 3022, 0)},
    "Law rune": {"rune": "Law rune", "talisman": "Law talisman", "level": 54, "bank": "Catherby", "ruins": Tile(2858, 3378, 0)},
    "Death rune": {"rune": "Death rune", "talisman": "Death talisman", "level": 65, "bank": "Edgeville", "ruins": Tile(3221, 3218, 0)},
}

DEFAULT_RUNE = "Air rune"

PICKPOCKET_TARGETS = [
    {"name": "Man", "level": 1},
    {"name": "Woman", "level": 1},
    {"name": "Farmer", "level": 10},
    {"name": "Warrior woman", "level": 25},
    {"name": "Al-Kharid warrior", "level": 25},
    {"name": "Rogue", "level": 32},
    {"name": "Guard", "level": 40},
    {"name": "Knight of Ardougne", "level": 55},
    {"name": "Watchman", "level": 65},
    {"name": "Paladin", "level": 70},
    {"name": "Hero", "level": 80},
]

ARDOUGNE_PICKPOCKET_TARGETS = ["Guard", "Knight of Ardougne", "Paladin", "Hero"]

HERBS = [
    {"key": "guam", "name": "Guam leaf", "id": 249, "unid_id": 199, "level": 3},
    {"key": "marrentill", "name": "Marrentill", "id": 251, "unid_id": 201, "level": 5},
    {"key": "tarromin", "name": "Tarromin", "id": 253, "unid_id": 203, "level": 11},
    {"key": "harralander", "name": "Harralander", "id": 255, "unid_id": 205, "level": 20},
    {"key": "ranarr", "name": "Ranarr weed", "id": 257, "unid_id": 207, "level": 25},
    {"key": "toadflax", "name": "Toadflax", "id": 2998, "unid_id": 3049, "level": 30},
    {"key": "irit", "name": "Irit leaf", "id": 259, "unid_id": 209, "level": 40},
    {"key": "avantoe", "name": "Avantoe", "id": 261, "unid_id": 211, "level": 48},
    {"key": "kwuarm", "name": "Kwuarm", "id": 263, "unid_id": 213, "level": 54},
    {"key": "snapdragon", "name": "Snapdragon", "id": 3000, "unid_id": 3051, "level": 59},
    {"key": "cadantine", "name": "Cadantine", "id": 265, "unid_id": 215, "level": 65},
    {"key": "lantadyme", "name": "Lantadyme", "id": 2481, "unid_id": 2485, "level": 67},
    {"key": "dwarf weed", "name": "Dwarf weed", "id": 267, "unid_id": 217, "level": 70},
    {"key": "torstol", "name": "Torstol", "id": 269, "unid_id": 219, "level": 75},
    {"key": "snake weed", "name": "Snake weed", "id": 1526, "unid_id": 1525, "level": 3},
    {"key": "ardrigal", "name": "Ardrigal", "id": 1528, "unid_id": 1527, "level": 3},
    {"key": "sito foil", "name": "Sito foil", "id": 1530, "unid_id": 1529, "level": 3},
    {"key": "volencia moss", "name": "Volencia moss", "id": 1532, "unid_id": 1531, "level": 3},
    {"key": "rogues purse", "name": "Rogues purse", "id": 1534, "unid_id": 1533, "level": 3},
]

COOKING_SURFACE_LOCS = [
    {"x": 2445, "z": 3188, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2459, "z": 3173, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2513, "z": 3427, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2523, "z": 3499, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2526, "z": 3319, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2542, "z": 3284, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2547, "z": 3322, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2549, "z": 3098, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2565, "z": 3154, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2565, "z": 3159, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 2565, "z": 3267, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2566, "z": 3104, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2568, "z": 3093, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 2570, "z": 3082, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2570, "z": 3254, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2571, "z": 3248, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2578, "z": 3198, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2591, "z": 3209, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2594, "z": 3335, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 2596, "z": 3214, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 2609, "z": 3476, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2615, "z": 3214, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2616, "z": 3396, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2617, "z": 3317, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2630, "z": 4731, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2632, "z": 3163, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2633, "z": 3176, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 2636, "z": 3170, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2637, "z": 3432, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2642, "z": 3355, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2648, "z": 3297, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2648, "z": 3355, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 2694, "z": 3498, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2695, "z": 3466, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2706, "z": 3404, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2711, "z": 3476, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2715, "z": 3476, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2733, "z": 3582, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2737, "z": 3460, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2746, "z": 3468, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2747, "z": 3580, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2758, "z": 4731, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2763, "z": 3274, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2787, "z": 3191, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2791, "z": 3199, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2798, "z": 3442, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 2800, "z": 3184, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2814, "z": 3161, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2817, "z": 3444, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2818, "z": 3455, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2822, "z": 3351, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2844, "z": 3367, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2856, "z": 3334, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2909, "z": 3529, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2917, "z": 3318, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2919, "z": 3557, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2922, "z": 9713, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2923, "z": 3573, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2931, "z": 3207, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 2932, "z": 3537, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2933, "z": 4698, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2967, "z": 3203, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2967, "z": 3331, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2970, "z": 3209, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2971, "z": 3328, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2988, "z": 3365, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3019, "z": 3237, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3024, "z": 3245, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3026, "z": 3259, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3030, "z": 3514, "level": 0, "name": "Fireplace", "debugname": "grandfireplace_oldbrick", "kind": "fire"},
    {"x": 3034, "z": 3297, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 3036, "z": 3342, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3036, "z": 3708, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3039, "z": 3367, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3046, "z": 3375, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3052, "z": 3356, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3054, "z": 3379, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 3089, "z": 3121, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 3095, "z": 3102, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3097, "z": 3367, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3100, "z": 3256, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3101, "z": 3281, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3104, "z": 3357, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 3151, "z": 9558, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3156, "z": 3410, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3160, "z": 3427, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3188, "z": 3352, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3205, "z": 3220, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 3212, "z": 3215, "level": 0, "name": "Cooking range", "debugname": "cooksquestrange", "kind": "oven"},
    {"x": 3214, "z": 3249, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3219, "z": 3388, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3219, "z": 3403, "level": 0, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
    {"x": 3221, "z": 3497, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3223, "z": 3497, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3225, "z": 3290, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 3229, "z": 3401, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3230, "z": 3196, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3232, "z": 3238, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 3236, "z": 3382, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3237, "z": 3151, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3237, "z": 3403, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3237, "z": 3409, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3240, "z": 3454, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3242, "z": 3394, "level": 0, "name": "Cooking pot", "debugname": "fireplacecookingpot", "kind": "fire"},
    {"x": 3244, "z": 3393, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3271, "z": 3180, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3271, "z": 3380, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3275, "z": 3500, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3280, "z": 3929, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3286, "z": 3486, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3286, "z": 3489, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3292, "z": 3202, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3318, "z": 3138, "level": 0, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3321, "z": 3137, "level": 0, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 2448, "z": 3510, "level": 1, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2482, "z": 3479, "level": 1, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2926, "z": 3545, "level": 1, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3026, "z": 3262, "level": 1, "name": "Fireplace", "debugname": "fireplace", "kind": "fire"},
    {"x": 3081, "z": 3508, "level": 1, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3143, "z": 3452, "level": 1, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3145, "z": 3452, "level": 1, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 3202, "z": 3401, "level": 1, "name": "Range", "debugname": "range", "kind": "oven"},
    {"x": 2612, "z": 3145, "level": 2, "name": "Fireplace", "debugname": "grandfireplace", "kind": "fire"},
]

COOKING_RANGE_LOCS = [Tile(2445, 3188, 0), Tile(2459, 3173, 0), Tile(2547, 3322, 0), Tile(2549, 3098, 0), Tile(2566, 3104, 0), Tile(2571, 3248, 0), Tile(2578, 3198, 0), Tile(2591, 3209, 0), Tile(2616, 3396, 0), Tile(2617, 3317, 0), Tile(2630, 4731, 0), Tile(2632, 3163, 0), Tile(2636, 3170, 0), Tile(2637, 3432, 0), Tile(2642, 3355, 0), Tile(2648, 3297, 0), Tile(2706, 3404, 0), Tile(2715, 3476, 0), Tile(2733, 3582, 0), Tile(2758, 4731, 0), Tile(2763, 3274, 0), Tile(2787, 3191, 0), Tile(2814, 3161, 0), Tile(2817, 3444, 0), Tile(2818, 3455, 0), Tile(2822, 3351, 0), Tile(2844, 3367, 0), Tile(2856, 3334, 0), Tile(2917, 3318, 0), Tile(2922, 9713, 0), Tile(2933, 4698, 0), Tile(2967, 3331, 0), Tile(2970, 3209, 0), Tile(2971, 3328, 0), Tile(2988, 3365, 0), Tile(3019, 3237, 0), Tile(3036, 3342, 0), Tile(3036, 3708, 0), Tile(3039, 3367, 0), Tile(3046, 3375, 0), Tile(3052, 3356, 0), Tile(3097, 3367, 0), Tile(3151, 9558, 0), Tile(3156, 3410, 0), Tile(3160, 3427, 0), Tile(3188, 3352, 0), Tile(3219, 3388, 0), Tile(3221, 3497, 0), Tile(3223, 3497, 0), Tile(3229, 3401, 0), Tile(3230, 3196, 0), Tile(3236, 3382, 0), Tile(3237, 3403, 0), Tile(3237, 3409, 0), Tile(3271, 3180, 0), Tile(3280, 3929, 0), Tile(3286, 3486, 0), Tile(3286, 3489, 0), Tile(3292, 3202, 0), Tile(3318, 3138, 0), Tile(2448, 3510, 1), Tile(2482, 3479, 1), Tile(3081, 3508, 1), Tile(3143, 3452, 1), Tile(3145, 3452, 1), Tile(3202, 3401, 1)]

CATHERBY_RANGE = {"stand": Tile(2817, 3443, 0), "loc": Tile(2817, 3444, 0), "loc_name": "Range", "kind": "range", "label": "Catherby range (bank house)", "notes": "Door/gate; good for both pier and bank cook modes"}

FISH_CAMP_COOK_PLANS = {
    "Catherby": {
        "pier": {"stand": Tile(2817, 3443, 0), "loc": Tile(2817, 3444, 0), "loc_name": "Range", "kind": "range", "label": "Catherby range (bank house)", "notes": "Door/gate; good for both pier and bank cook modes"},
        "bank": {"stand": Tile(2817, 3443, 0), "loc": Tile(2817, 3444, 0), "loc_name": "Range", "kind": "range", "label": "Catherby range (bank house)", "notes": "Door/gate; good for both pier and bank cook modes"},
    },
    "Seers (fly fishing)": {
        "pier": {"approach": Tile(2740, 3570, 0), "stand": Tile(2735, 3581, 0), "loc": Tile(2733, 3582, 0), "loc_name": "Range", "kind": "range", "label": "Sinclair mansion range (Large-door approach)", "notes": "approach→open Large door→east-of-range stand"},
        "bank": {"approach": Tile(2713, 3484, 0), "stand": Tile(2716, 3477, 0), "loc": Tile(2715, 3476, 0), "loc_name": "Range", "kind": "range", "label": "Seers village range (near bank)", "notes": "approach Door@2713,3483 → stand north of range (interior)"},
    },
    "Fishing Guild": {
        "pier": {"stand": Tile(2616, 3395, 0), "loc": Tile(2616, 3396, 0), "loc_name": "Range", "kind": "range", "label": "Ardougne range S of guild", "notes": "Outside guild fence; walk after bank/dock"},
    },
    "Barbarian Village": {
        "pier": {"stand": Tile(3079, 3444, 0), "loc": Tile(3078, 3445, 0), "loc_name": "Fire", "kind": "fire", "label": "Barb outdoor fires", "notes": "No Range in village; cook on Fire"},
    },
    "Draynor Village": {
        "pier": {"approach": Tile(3102, 3258, 0), "stand": Tile(3100, 3257, 0), "loc": Tile(3100, 3256, 0), "loc_name": "Fireplace", "kind": "fireplace", "label": "Draynor house fireplace", "notes": "approach Door@3101,3258 → stand north of fireplace (interior)"},
        "bank": {"approach": Tile(3102, 3258, 0), "stand": Tile(3100, 3257, 0), "loc": Tile(3100, 3256, 0), "loc_name": "Fireplace", "kind": "fireplace", "label": "Draynor house fireplace", "notes": "approach Door@3101,3258 → stand north of fireplace (interior)"},
    },
}

COOK_LOCATIONS = [
    {
        "name": "Varrock East",
        "bank": {"name": "Varrock East", "tile": Tile(3253, 3420, 0)},
        "surface": {"stand": Tile(3237, 3408, 0), "loc_name": "Range", "kind": "oven", "loc": Tile(3237, 3409, 0), "arrive_radius": 2, "label": "Range @ 3237,3409"},
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Varrock West",
        "bank": {"name": "Varrock West", "tile": Tile(3185, 3440, 0)},
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Al Kharid",
        "bank": {"name": "Al Kharid", "tile": Tile(3269, 3167, 0)},
        "surface": {"stand": Tile(3271, 3179, 0), "loc_name": "Range", "kind": "oven", "loc": Tile(3271, 3180, 0), "arrive_radius": 2, "label": "Range @ 3271,3180"},
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Draynor",
        "bank": {"name": "Draynor", "tile": Tile(3093, 3243, 0)},
        "surface": {"stand": Tile(3100, 3257, 0), "approach": Tile(3102, 3258, 0), "loc_name": "Fireplace", "kind": "fire", "loc": Tile(3100, 3256, 0), "arrive_radius": 0, "label": "Draynor house fireplace"},
        "obstacles": ["door", "gate"],
        "verified": True,
    },
    {
        "name": "Falador East",
        "bank": {"name": "Falador East", "tile": Tile(3013, 3355, 0)},
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Falador West",
        "bank": {"name": "Falador West", "tile": Tile(2946, 3369, 0)},
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Edgeville",
        "bank": {"name": "Edgeville", "tile": Tile(3094, 3493, 0)},
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Seers",
        "bank": {"name": "Seers", "tile": Tile(2725, 3491, 0)},
        "surface": {"stand": Tile(2716, 3477, 0), "approach": Tile(2713, 3484, 0), "loc_name": "Range", "kind": "oven", "loc": Tile(2715, 3476, 0), "arrive_radius": 0, "label": "Seers village range (near bank)"},
        "obstacles": ["door", "gate"],
        "verified": True,
    },
    {
        "name": "Catherby",
        "bank": {"name": "Catherby", "tile": Tile(2809, 3441, 0)},
        "surface": {"stand": Tile(2817, 3443, 0), "loc_name": "Range", "kind": "oven", "loc": Tile(2817, 3444, 0), "arrive_radius": 0, "label": "Catherby range (bank house)"},
        "obstacles": ["door", "gate"],
        "verified": True,
    },
    {
        "name": "Yanille",
        "bank": {"name": "Yanille", "tile": Tile(2612, 3092, 0)},
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Ardougne West",
        "bank": {"name": "Ardougne West", "tile": Tile(2616, 3332, 0)},
        "surface": {"stand": Tile(2617, 3316, 0), "loc_name": "Range", "kind": "oven", "loc": Tile(2617, 3317, 0), "arrive_radius": 2, "label": "Range @ 2617,3317"},
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Ardougne East",
        "bank": {"name": "Ardougne East", "tile": Tile(2655, 3283, 0)},
        "surface": {"stand": Tile(2648, 3296, 0), "loc_name": "Range", "kind": "oven", "loc": Tile(2648, 3297, 0), "arrive_radius": 2, "label": "Range @ 2648,3297"},
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Canifis",
        "bank": {
            "name": "Canifis",
            "tile": Tile(3512, 3480, 0),
            "requires": {"quest": "Priest in Peril"},
        },
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Shilo Village",
        "bank": {
            "name": "Shilo Village",
            "tile": Tile(2852, 2954, 0),
            "requires": {"quest": "Shilo Village"},
            "npc_access": {"name": "Banker", "op": "Bank"},
        },
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Zanaris",
        "bank": {
            "name": "Zanaris",
            "tile": Tile(3153, 9576, 0),
            "requires": {"quest": "Lost City", "setting": "useZanarisBank"},
            "npc_access": {"name": "Banker", "op": "Bank"},
        },
        "surface": {"stand": Tile(3151, 9557, 0), "loc_name": "Range", "kind": "oven", "loc": Tile(3151, 9558, 0), "arrive_radius": 2, "label": "Range @ 3151,9558"},
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Fishing Guild",
        "bank": {
            "name": "Fishing Guild",
            "tile": Tile(2586, 3420, 0),
            "requires": {
                "skill": {"name": "fishing", "level": 68},
            },
        },
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Legends Guild",
        "bank": {
            "name": "Legends Guild",
            "tile": Tile(2732, 3378, 2),
            "requires": {"quest": "Legends Quest"},
            "npc_access": {"name": "Banker", "op": "Bank"},
        },
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Shantay Pass",
        "bank": {
            "name": "Shantay Pass",
            "tile": Tile(3308, 3120, 0),
            "access": {"name": "Shantay chest", "op": "Open"},
        },
        "surface": {"stand": Tile(3318, 3137, 0), "loc_name": "Range", "kind": "oven", "loc": Tile(3318, 3138, 0), "arrive_radius": 2, "label": "Range @ 3318,3138"},
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Mage Arena",
        "bank": {
            "name": "Mage Arena",
            "tile": Tile(2542, 4714, 0),
            "requires": {"setting": "useMageBank"},
            "approach": Tile(3091, 3958, 0),
            "npc_access": {"name": "Gundai", "op": "Talk-to", "choose": "I'd like to access my bank account"},
        },
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Grand Tree",
        "bank": {"name": "Grand Tree", "tile": Tile(2449, 3482, 1)},
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
    {
        "name": "Duel Arena",
        "bank": {
            "name": "Duel Arena",
            "tile": Tile(3382, 3269, 0),
            "access": {
                "name": "Open chest",
                "op": "Bank",
                "open_first": {"name": "Closed chest", "op": "Open"},
            },
        },
        "surface": None,
        "obstacles": ["door", "gate"],
        "verified": False,
    },
]

WALK_DESTINATIONS = [
    {"name": "Lumbridge", "tile": Tile(3221, 3218, 0)},
    {"name": "Varrock", "tile": Tile(3213, 3424, 0)},
    {"name": "Falador", "tile": Tile(2965, 3378, 0)},
    {"name": "Ardougne", "tile": Tile(2661, 3301, 0)},
    {"name": "Rellekka", "tile": Tile(2668, 3660, 0)},
    {"name": "Taverley", "tile": Tile(2895, 3435, 0)},
    {"name": "Draynor", "tile": Tile(3093, 3243, 0)},
    {"name": "Al Kharid", "tile": Tile(3269, 3167, 0)},
    {"name": "Edgeville", "tile": Tile(3094, 3493, 0)},
    {"name": "Seers' Village", "tile": Tile(2725, 3491, 0)},
    {"name": "Catherby", "tile": Tile(2809, 3441, 0)},
    {"name": "Yanille", "tile": Tile(2612, 3092, 0)},
]

FIRE_SPOTS = {
    "Varrock East": {"bank": Tile(3253, 3420, 0), "x0": 3232, "x1": 3284, "z0": 3428, "z1": 3430},
    "Varrock West": {"bank": Tile(3185, 3440, 0), "x0": 3168, "x1": 3209, "z0": 3428, "z1": 3431},
    "Draynor": {"bank": Tile(3093, 3243, 0), "x0": 3072, "x1": 3097, "z0": 3247, "z1": 3249},
    "Seers": {"bank": Tile(2725, 3491, 0), "x0": 2695, "x1": 2733, "z0": 3484, "z1": 3485},
}

LOG_LEVELS = {
    "Logs": 1,
    "Oak logs": 15,
    "Willow logs": 30,
    "Maple logs": 45,
    "Yew logs": 60,
    "Magic logs": 75,
}

SPELL_DB = {
    "Wind Strike": {
        "ssb": 0,
        "level": 1,
        "runes": [
            {"rune": "Mind rune", "count": 1},
            {"rune": "Air rune", "count": 1},
        ],
    },
    "Water Strike": {
        "ssb": 1,
        "level": 5,
        "runes": [
            {"rune": "Mind rune", "count": 1},
            {"rune": "Water rune", "count": 1},
            {"rune": "Air rune", "count": 1},
        ],
    },
    "Earth Strike": {
        "ssb": 2,
        "level": 9,
        "runes": [
            {"rune": "Mind rune", "count": 1},
            {"rune": "Earth rune", "count": 2},
            {"rune": "Air rune", "count": 1},
        ],
    },
    "Fire Strike": {
        "ssb": 3,
        "level": 13,
        "runes": [
            {"rune": "Mind rune", "count": 1},
            {"rune": "Fire rune", "count": 3},
            {"rune": "Air rune", "count": 2},
        ],
    },
    "Wind Bolt": {
        "ssb": 4,
        "level": 17,
        "runes": [
            {"rune": "Chaos rune", "count": 1},
            {"rune": "Air rune", "count": 2},
        ],
    },
    "Water Bolt": {
        "ssb": 5,
        "level": 23,
        "runes": [
            {"rune": "Chaos rune", "count": 1},
            {"rune": "Water rune", "count": 2},
            {"rune": "Air rune", "count": 2},
        ],
    },
    "Earth Bolt": {
        "ssb": 6,
        "level": 29,
        "runes": [
            {"rune": "Chaos rune", "count": 1},
            {"rune": "Earth rune", "count": 3},
            {"rune": "Air rune", "count": 2},
        ],
    },
    "Fire Bolt": {
        "ssb": 7,
        "level": 35,
        "runes": [
            {"rune": "Chaos rune", "count": 1},
            {"rune": "Fire rune", "count": 4},
            {"rune": "Air rune", "count": 3},
        ],
    },
    "Wind Blast": {
        "ssb": 8,
        "level": 41,
        "runes": [
            {"rune": "Death rune", "count": 1},
            {"rune": "Air rune", "count": 3},
        ],
    },
    "Water Blast": {
        "ssb": 9,
        "level": 47,
        "runes": [
            {"rune": "Death rune", "count": 1},
            {"rune": "Water rune", "count": 3},
            {"rune": "Air rune", "count": 3},
        ],
    },
    "Earth Blast": {
        "ssb": 10,
        "level": 53,
        "runes": [
            {"rune": "Death rune", "count": 1},
            {"rune": "Earth rune", "count": 4},
            {"rune": "Air rune", "count": 3},
        ],
    },
    "Fire Blast": {
        "ssb": 11,
        "level": 59,
        "runes": [
            {"rune": "Death rune", "count": 1},
            {"rune": "Fire rune", "count": 5},
            {"rune": "Air rune", "count": 4},
        ],
    },
    "Wind Wave": {
        "ssb": 12,
        "level": 62,
        "runes": [
            {"rune": "Blood rune", "count": 1},
            {"rune": "Air rune", "count": 5},
        ],
    },
    "Water Wave": {
        "ssb": 13,
        "level": 65,
        "runes": [
            {"rune": "Blood rune", "count": 1},
            {"rune": "Water rune", "count": 7},
            {"rune": "Air rune", "count": 5},
        ],
    },
    "Earth Wave": {
        "ssb": 14,
        "level": 70,
        "runes": [
            {"rune": "Blood rune", "count": 1},
            {"rune": "Earth rune", "count": 7},
            {"rune": "Air rune", "count": 5},
        ],
    },
    "Fire Wave": {
        "ssb": 15,
        "level": 75,
        "runes": [
            {"rune": "Blood rune", "count": 1},
            {"rune": "Fire rune", "count": 7},
            {"rune": "Air rune", "count": 5},
        ],
    },
}
