# rs2004.catalogs: rs2b0t's world catalogs and behaviours. See docs/ScriptingApi.md, "Catalogs and behaviours".

from typing import Any, Callable, Optional, Sequence, Union

from __builtins__ import Tile, Task, AbstractBot, Wait

Count = Callable[[str], int]
Level = Callable[[str], int]

class Record:
    def __getattr__(self, name: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def keys(self) -> list[str]: ...

# Tools

class ToolTier:
    name: str
    level: int
    attack_level: int
    def __init__(self, name: str, level: int, attack_level: int = 1) -> None: ...

class ToolReq:
    kind: str
    skill: Optional[str]
    tiers: Optional[list[ToolTier]]
    label: Optional[str]
    name: Optional[str]
    min: int
    restock: int
    equip: bool

class ToolRestockStep:
    name: str
    qty: int
    equip: bool

PICKAXES: list[ToolTier]
AXES: list[ToolTier]
TINDERBOX: str
HAMMER: str
KNIFE: str
CHISEL: str
NEEDLE: str
def tool_attack_level(name: str) -> int: ...
def can_wield_tool(name: str, attack_level: int) -> bool: ...
def pickaxe_req(equip: bool = True) -> ToolReq: ...
def axe_req(equip: bool = True) -> ToolReq: ...
def exact_tool(name: str, min: int = 1, restock: Optional[int] = None, equip: bool = False) -> ToolReq: ...
def tinderbox_req() -> ToolReq: ...
def best_from_tiers(level: int, tiers: Sequence[ToolTier], available: Callable[[str], bool]) -> Optional[str]: ...
def best_pickaxe(mining_level: int, available: Callable[[str], bool]) -> Optional[str]: ...
def best_axe(woodcutting_level: int, available: Callable[[str], bool]) -> Optional[str]: ...
def tool_keep_names(reqs: Sequence[ToolReq]) -> list[str]: ...
def has_tool_req(req: ToolReq, skill_level: Level, count: Count) -> bool: ...
def has_all_tools(reqs: Sequence[ToolReq], skill_level: Level, count: Count) -> bool: ...
def missing_tool_labels(reqs: Sequence[ToolReq], skill_level: Level, count: Count) -> list[str]: ...
def tool_kit_label(reqs: Sequence[ToolReq], skill_level: Level, count: Count) -> str: ...
def tool_restock_plan(reqs: Sequence[ToolReq], skill_level: Level, inv_count: Count, bank_count: Count) -> list[ToolRestockStep]: ...
def bank_has_better_gather_tool(reqs: Sequence[ToolReq], skill_level: Level, inv_count: Count, bank_count: Count) -> bool: ...
def tools_needing_equip(reqs: Sequence[ToolReq], skill_level: Level, count: Count, worn: Callable[[str], bool]) -> list[str]: ...
def best_held_tool_names(reqs: Sequence[ToolReq], skill_level: Level, count: Count) -> list[str]: ...
def surplus_held_tool_names(reqs: Sequence[ToolReq], skill_level: Level, count: Count) -> list[str]: ...

# Getting tools

class ToolVendor:
    keeper: str
    stand: Tile
    bank_stand: Tile
    hop_from: Optional[Tile]
    hop_loc: Optional[str]
    hop_action: Optional[str]

class ShopOffer:
    name: str
    cost: int
    vendor: ToolVendor

class ToolAcquirePlan:
    kind: str
    name: Optional[str]
    cost: int
    qty: int
    vendor: Optional[ToolVendor]
    equip: bool
    reason: str
    broken_name: Optional[str]
    label: Optional[str]
    prefer: list[str]
    bar: Optional[str]
    smith_level: int
    vendor_bank: Optional[Tile]
    anvil_stand: Optional[Tile]

class AcquireWorld:
    def __init__(self, skill_level: Level, held_count: Count, inv_count: Count, bank_count: Count, worn: Callable[[str], bool]) -> None: ...

COINS: str
BROKEN_AXE: str
TOOL_ACQUIRE_OPTIONS: list[str]
FORGETFUL_BANK_ODDS: int
BOB_VENDOR: ToolVendor
NURMOF_VENDOR: ToolVendor
GERRANT_VENDOR: ToolVendor
HARRY_VENDOR: ToolVendor
GERRANT_ONLY_FISHING: list[str]
VARROCK_ANVIL_STAND: Tile
VARROCK_ANVIL_BANK: Tile
PICKAXE_SHOP_COSTS: dict[str, int]
AXE_SHOP_COSTS: dict[str, int]
FISHING_SHOP_COSTS: dict[str, int]
AXE_SMITH_LEVEL: dict[str, int]
AXE_BAR_FOR: dict[str, str]
def parse_tool_acquire_mode(raw: Any) -> str: ...
def best_owned_tier(level: int, tiers: Sequence[ToolTier], count: Count) -> Optional[str]: ...
def pickaxe_shop_offers() -> list[ShopOffer]: ...
def axe_shop_offers() -> list[ShopOffer]: ...
def best_affordable_shop_tier(level: int, tiers: Sequence[ToolTier], offers: Sequence[ShopOffer], coins: int, owned: Optional[str]) -> Optional[ShopOffer]: ...
def best_smithable_axe(woodcutting_level: int, smithing_level: int, owned: Optional[str], bar_count: Count, has_hammer: bool) -> Optional[tuple[str, str, int]]: ...
def plan_broken_tool_repair(held_or_worn: Callable[[str], bool]) -> Optional[ToolAcquirePlan]: ...
def plan_pickaxe_acquire(world: AcquireWorld, upgrade: bool = False) -> Optional[ToolAcquirePlan]: ...
def plan_axe_acquire(world: AcquireWorld, upgrade: bool = False) -> Optional[ToolAcquirePlan]: ...
def plan_gather_tool_acquire(reqs: Sequence[ToolReq], world: AcquireWorld, upgrade: bool = False) -> Optional[ToolAcquirePlan]: ...
def fishing_vendor_for(name: str, near: Optional[Tile] = None) -> ToolVendor: ...
def fishing_shop_cost(name: str) -> Optional[int]: ...
def is_fishing_bait_piece(piece: FishingGearPiece) -> bool: ...
def with_bait_target(method: FishingMethod, bait_qty: int) -> list[FishingGearPiece]: ...
def plan_fishing_gear_buys(method: FishingMethod, world: AcquireWorld, near: Optional[Tile] = None, bait_qty: int = 1000) -> list[ToolAcquirePlan]: ...
def plan_fishing_gear_acquire(method: FishingMethod, world: AcquireWorld, near: Optional[Tile] = None, bait_qty: int = 1000) -> Optional[ToolAcquirePlan]: ...
def fishing_gear_shop_cart(method: FishingMethod, world: AcquireWorld, near: Optional[Tile] = None, bait_qty: int = 1000) -> list[ToolAcquirePlan]: ...
def buy_plans_cost(plans: Sequence[ToolAcquirePlan]) -> int: ...
def coins_to_withdraw(need: int, inv_coins: int) -> int: ...
def can_fund_plan(plan: ToolAcquirePlan, inv_coins: int, bank_coins: int) -> bool: ...
def acquire_keep_names(plan: ToolAcquirePlan, extra: Optional[Sequence[str]] = None) -> list[str]: ...
def shopable_missing_fishing_gear(gear: Sequence[FishingGearPiece], count: Count) -> list[str]: ...
def needs_tool_vendor_surface_hop(vendor: ToolVendor, here: Optional[Tile]) -> bool: ...
def walk_to_tool_vendor(vendor: ToolVendor, log: Optional[Callable[[str], None]] = None) -> Wait[bool]: ...

# Fishing and mining

class FishingGearPiece:
    name: str
    min: int
    restock: int

class FishingMethod:
    name: str
    op: str
    pair: str
    gear: list[FishingGearPiece]

WHIRLPOOL_IDS: list[int]
FISHING_METHODS: list[FishingMethod]
FISHING_METHOD_OPTIONS: list[str]
ALL_FISHING_GEAR_NAMES: list[str]
def resolve_fish_method(name: str) -> FishingMethod: ...
def gear_keep_names(method: FishingMethod) -> list[str]: ...
def has_fishing_gear(method: FishingMethod, count: Count) -> bool: ...
def missing_fishing_gear(method: FishingMethod, count: Count) -> list[FishingGearPiece]: ...
def gear_label(method: FishingMethod) -> str: ...
def fishing_restock_plan(method: FishingMethod, inv_count: Count, bank_count: Count) -> list[tuple[str, int]]: ...
def spot_matches_method(actions: Sequence[str], method: FishingMethod) -> bool: ...

ROCK_OPTIONS: list[str]
ROCK_TYPES: dict[str, list[int]]
QUEST_ROCK_TYPES: dict[str, list[int]]
ROCK_TIER_ORDER: list[str]
GAS_ROCK_IDS: list[int]
GAS_ROCK_TICKS: int
BROKEN_PICKAXE: str
def rock_tier_by_id(id: int) -> int: ...
def resolve_rock_ids(names: Sequence[str]) -> list[int]: ...

# Gathering camps

DEFAULT_BOOTH_NAME: str
DEFAULT_BOOTH_OP: str
DEFAULT_CAMP_RADIUS: int
DEFAULT_CHASE_RADIUS: int
MAP_SQUARE: int
USE_CLOSEST: str
USE_START_POSITION: str
USE_CUSTOM_POSITION: str
LOCAL_MINE_PREFER_RADIUS: int
FISHING_LOCATIONS: list[Record]
FISHING_LOCATION_OPTIONS: list[str]
SHILO_WATER_VENDOR: Record
WOODCUTTING_LOCATIONS: list[Record]
WOODCUTTING_LOCATION_OPTIONS: list[str]
ENT_NPC_IDS: list[int]
ENT_LIFE_TICKS: int
MINING_LOCATIONS: list[Record]
MINING_LOCATION_OPTIONS: list[str]
MINING_LOCATION_OPTION_LABELS: dict[str, str]
def resolve_camp_radius(camp_radius: Optional[int], fallback: int = 64) -> int: ...
def resolve_chase_radius(chase_radius: Optional[int], fallback: int = 40) -> int: ...
def same_map_square(a: Tile, b: Tile) -> bool: ...
def bank_distance(start: Tile, tile: Tile) -> float: ...
def location_options(table: Sequence[Record]) -> list[str]: ...
def booth_fields(loc: Optional[Record]) -> tuple[str, str]: ...
def resolve_gathering_location(setting: str, start_tile: Tile, table: Sequence[Record]) -> Optional[Record]: ...
def resolve_fishing_location(setting: str, start_tile: Tile) -> Optional[Record]: ...
def resolve_mining_location(setting: str, start_tile: Tile) -> Optional[Record]: ...
def resolve_woodcutting_location(setting: str, start_tile: Tile) -> Optional[Record]: ...
def mining_location_label(loc: Record) -> str: ...
def is_ent_npc_id(id: int) -> bool: ...
def ent_npc_on_tile(npcs: Sequence[Any], tile: Tile) -> bool: ...
def pick_nearest_prefer_local(candidates: Sequence[Any], distance: Callable[[Any], float], prefer_radius: int = 12) -> Any: ...
def pick_bucket_nearest(candidates: Sequence[Any], bucket: Callable[[Any], int], distance: Callable[[Any], float], prefer_radius: int = 12) -> Any: ...
def should_cooldown_gather_tile(got_product: bool, other_targets: bool) -> bool: ...

# Other tables

COW_LOCATIONS: list[Record]
COW_LOCATION_OPTIONS: list[str]
DRAYNOR_BANK: Tile
FALADOR_EAST_BANK: Tile
ARDOUGNE_WEST_BANK: Tile
AL_KHARID_BANK: Tile
TOLL_COIN_TARGET: int
def is_cow_field_loot_tile(anchor: Tile, leash_radius: int, tile: Tile) -> bool: ...
def nearest_cow_location(tile: Tile) -> Record: ...
def resolve_cow_location(setting: str, start: Tile) -> Optional[Record]: ...
def needs_toll_coins(location: Optional[Record], enabled: bool) -> bool: ...
def cow_bank_destination(location: Optional[Record], toll_enabled: bool) -> Optional[tuple[str, Tile]]: ...
def should_bootstrap_toll_coins(location: Optional[Record], start: Tile, coins: int, enabled: bool) -> bool: ...
RUNES: dict[str, Record]
RUNE_OPTIONS: list[str]
DEFAULT_RUNE: str
PICKPOCKET_TARGETS: list[Record]
PICKPOCKET_TARGET_NAMES: list[str]
ARDOUGNE_PICKPOCKET_TARGETS: list[str]
HERBS: list[Record]
HERB_OPTIONS: list[str]
def shop_db() -> dict[str, dict[str, Any]]: ...
def shops_selling(item: str) -> list[tuple[str, dict[str, Any]]]: ...
WALK_DESTINATIONS: list[Record]
WALK_OPTIONS: list[str]
def resolve_destination(name: str) -> Optional[Record]: ...
COOKING_SURFACE_LOCS: list[Record]
COOKING_RANGE_LOCS: list[Tile]
CATHERBY_RANGE: Record
FISH_CAMP_COOK_PLANS: dict[str, Record]
COOK_LOCATIONS: list[Record]
COOK_LOCATION_OPTIONS: list[str]
def range_stand_from_loc(loc: Tile) -> Tile: ...
def nearest_cooking_range(origin: Tile, max_cheb: int = 64) -> Optional[Record]: ...
def cook_surface_for_fish_camp(camp_name: str, role: str = 'pier') -> Optional[Record]: ...
def resolve_fish_camp_cook_surface(camp_name: Optional[str], spot: Tile, max_cheb: int = 64, role: str = 'pier') -> Optional[Record]: ...
def nearest_cook_surface(origin: Tile, max_cheb: int = 20) -> Optional[Record]: ...
def cook_location(name: str) -> Optional[Record]: ...
def resolve_cook_location(setting: str, start: Tile, unlocked: Optional[Callable[[Record], bool]] = None) -> Optional[Record]: ...
FIRE_SPOTS: dict[str, Record]
FIRE_SPOT_OPTIONS: list[str]
LOG_LEVELS: dict[str, int]
BURN_MODE_OPTIONS: list[str]
def parse_burn_mode(label: str) -> str: ...
def logs_for_tree(tree_name: str) -> str: ...
def firemaking_level_for_logs(log_name: str) -> Optional[int]: ...
def resolve_fire_spot(name: str) -> Optional[tuple[str, Record]]: ...
def nearest_fire_spot(start: Tile) -> Optional[tuple[str, Record]]: ...
def local_fire_plot(origin: Tile, half: int = 8) -> Record: ...
def expand_local_fire_plot(plot: Record, grow_by: int = 4, max_half: int = 24) -> Optional[Record]: ...
def in_fire_plot(tile: Tile, plot: Record) -> bool: ...
def should_burn_full_load(mode: str, inventory_full: bool, log_count: int, has_tinderbox: bool) -> bool: ...

# Combat

FOOD_OPTIONS: list[str]
FOOD_FORMS: dict[str, list[str]]
FOOD_HEAL: dict[str, int]
MIN_EAT_HP: int
URGENT_HP_FRACTION: float
def food_forms(food_name: str) -> list[str]: ...
def is_food_item(name: Optional[str], food_name: str) -> bool: ...
def is_edible_food(item: Any, food_name: str) -> bool: ...
def food_count(items: Sequence[Any], food_name: str) -> int: ...
def food_heal_amount(food_name: str) -> int: ...
def eat_at_hp_threshold(max_hp: int, heal: int, min_hp: int = 5) -> int: ...
def should_eat_to_use_food(hp: int, max_hp: int, heal: int, count: int, min_hp: int = 5) -> bool: ...
def should_eat_food(food_name: str, hp: int, max_hp: int, count: int, min_hp: int = 5) -> bool: ...
def should_hold_eat(attacked_this_tick: bool, hp_fraction: float, urgent_at: float = 0.35) -> bool: ...

class AttackClock:
    def observe(self, animation: int, tick: int) -> None: ...
    def attacked_this_tick(self, tick: int) -> bool: ...
    def reset(self) -> None: ...

def swing_started_this_tick() -> bool: ...
def bury_one_in_fight(bone_name: str) -> Wait[bool]: ...

class BoostPotion:
    skill: str
    short: str
    flask: str
    doses: list[str]

class PotionPlan:
    potion: BoostPotion
    flask: str
    want: int

SUPER_ATTACK: BoostPotion
SUPER_STRENGTH: BoostPotion
SUPER_DEFENCE: BoostPotion
SUPER_SET: list[BoostPotion]
RANGING_POTION: BoostPotion
BOOST_POTIONS: list[BoostPotion]
EMPTY_VIAL: str
BOOST_FLOOR: float
SPELL_DB: dict[str, dict[str, Any]]
def boost_faded(base: int, effective: int, floor: float = 0.1) -> bool: ...
def ranging_plan(carry: Sequence[CarryEntry]) -> PotionPlan: ...
def planned_potions(carry: Sequence[CarryEntry], potions: Optional[Sequence[BoostPotion]] = None) -> list[PotionPlan]: ...
def potion_to_sip(plans: Sequence[PotionPlan], held: Callable[[PotionPlan], int], levels: Callable[[str], tuple[int, int]]) -> Optional[PotionPlan]: ...
def combat_keep_names(food: str, style: str, spell: Optional[str] = None, ammo: Optional[str] = None, weapon: Optional[str] = None, extra: Optional[Sequence[str]] = None) -> list[str]: ...

# Loadouts

SLOTS: list[str]

class CarryEntry:
    item: str
    qty: int
    def __init__(self, item: str, qty: int) -> None: ...

class Loadout:
    name: str
    worn: dict[str, str]
    carry: list[CarryEntry]
    def __init__(self, name: str, worn: Optional[dict[str, str]] = None, carry: Optional[list[CarryEntry]] = None) -> None: ...

def parse_loadouts(raw: Any) -> list[Loadout]: ...
def upsert_loadout(loadouts: Sequence[Loadout], loadout: Loadout) -> list[Loadout]: ...
def remove_loadout(loadouts: Sequence[Loadout], name: str) -> list[Loadout]: ...
def unique_name(loadouts: Sequence[Loadout], base: str) -> str: ...
def selected_loadout(settings: Any) -> Optional[Loadout]: ...
def food_of(loadout: Optional[Loadout], fallback: str, is_food: Optional[Callable[[str], bool]] = None) -> str: ...
def gear_of(loadout: Optional[Loadout]) -> list[str]: ...
def supplies_of(loadout: Optional[Loadout]) -> list[CarryEntry]: ...
def weapon_of(loadout: Optional[Loadout], fallback: Optional[str] = None) -> Optional[str]: ...
def script_food(settings: Any, fallback: str) -> str: ...
def script_foods(settings: Any, fallback: Sequence[str]) -> list[str]: ...

# Trading partners

DEFAULT_TRADE_RANGE: int
MULE_MODE_OPTIONS: list[str]
def parse_partner_list(raw: str) -> list[str]: ...
def names_match(a: str, b: str) -> bool: ...
def is_configured_partner(name: Optional[str], partners: Sequence[str]) -> bool: ...
def count_offer_by_name(items: Sequence[Any], item_name: str) -> int: ...
def count_offer_matching(items: Sequence[Any], test: Callable[[str], bool]) -> int: ...
def decide_receiver_offer_screen(partner_header: Optional[str], partners: Sequence[str], my_offer_slots: int, their_product_count: int) -> tuple[str, ...]: ...
def decide_giver_offer_screen(my_offer_slots: int) -> str: ...
def parse_mule_mode(raw: str) -> str: ...
def mule_gatherer_handoff_active(mode: str, partners: Sequence[str], power_mode: bool) -> bool: ...
def mule_receiver_active(mode: str, partners: Sequence[str]) -> bool: ...
def mule_cooker_active(mode: str, partners: Sequence[str]) -> bool: ...
def mule_supplier_active(mode: str, partners: Sequence[str], power_mode: bool) -> bool: ...
def mule_non_gatherer_active(mode: str, partners: Sequence[str]) -> bool: ...

# Tasks

class ItemNeed:
    name: str
    count: int
    source: tuple[Any, ...]
    def __init__(self, name: str, count: int, source: tuple[Any, ...]) -> None: ...

def held(name: str) -> int: ...
def has_all(needs: Sequence[ItemNeed]) -> bool: ...

class AcquireTask(Task):
    def __init__(self, bot: AbstractBot, needs: Sequence[ItemNeed]) -> None: ...

class ContinueDialog(Task):
    def __init__(self, on_continue: Optional[Callable[[], None]] = None) -> None: ...

class DeathRecovery(Task):
    def __init__(self, bot: AbstractBot, anchor: Tile, radius: int = 6, needs: Optional[Sequence[ItemNeed]] = None, on_death: Optional[Callable[[], None]] = None, on_recovered: Optional[Callable[[], None]] = None, walk_back: Optional[Callable[[], Any]] = None) -> None: ...

class AnchorHost:
    anchor: Tile
    leash_radius: int
    def __init__(self, anchor: Tile, leash_radius: int, log: Optional[Callable[[str], None]] = None) -> None: ...

HOME_ARRIVE_RADIUS: int
def should_walk_home_to_gather_anchor(dist_to_anchor: Optional[float], arrive_radius: int = 8) -> bool: ...
def should_soft_home_from_gather_miss(dist_to_anchor: Optional[float], leash: int = 64) -> bool: ...
def beyond_leash(host: AnchorHost, here: Optional[Tile], slack: int = 0) -> bool: ...
def tile_within_leash(host: AnchorHost, tile: Tile, slack: int = 0) -> bool: ...
def resolve_run_anchor(here: Tile, location_spot: Optional[Tile]) -> Tile: ...
def create_return_to_anchor_task(host: AnchorHost, slack: int = 6, arrive_radius: int = 8, timeout_ms: int = 90000, long_range_tiles: int = 0, suppress: Optional[Callable[[], bool]] = None) -> Task: ...

class _Sustain:
    def set(self, hook: Optional[Callable[[], Any]]) -> None: ...
    def run(self) -> Wait[None]: ...

sustain: _Sustain
