# Embeds the Python standard library in the executable. Run in script mode:
#   cmake -DSTDLIB_DIR=<src/Script/Stdlib> -DOUTPUT=<file.cpp> -P EmbedStdlib.cmake
# Each .py file becomes a byte array rather than a string literal, because MSVC limits a string literal to
# 64 KB. Every array ends in a 0 that the source's length leaves out.

file(GLOB_RECURSE FILES RELATIVE "${STDLIB_DIR}" "${STDLIB_DIR}/*.py")
list(SORT FILES)

set(ARRAYS "")
set(ENTRIES "")
set(INDEX 0)
foreach(FILE IN LISTS FILES)
    file(READ "${STDLIB_DIR}/${FILE}" HEX HEX)
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," BYTES "${HEX}")
    string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){32})" "\\1\n        " BYTES "${BYTES}")
    string(APPEND ARRAYS "    const unsigned char FILE_${INDEX}[] = {\n        ${BYTES}0x00\n    };\n\n")
    string(APPEND ENTRIES "            {\"${FILE}\", AsText(FILE_${INDEX})},\n")
    math(EXPR INDEX "${INDEX} + 1")
endforeach()

set(CONTENT "// Generated by cmake/EmbedStdlib.cmake from src/Script/Stdlib. Don't edit.
#include \"Script/Stdlib.hpp\"

namespace
{
${ARRAYS}    template <std::size_t SIZE>
    std::string_view AsText(const unsigned char (&bytes)[SIZE])
    {
        return {reinterpret_cast<const char*>(bytes), SIZE - 1};
    }
}

std::span<const StdlibFile_s> Stdlib::GetFiles()
{
    static const auto files = std::to_array<StdlibFile_s>({
${ENTRIES}    });
    return files;
}
")

# Rewriting an unchanged file would rebuild everything that depends on it.
set(CURRENT "")
if(EXISTS "${OUTPUT}")
    file(READ "${OUTPUT}" CURRENT)
endif()
if(NOT CURRENT STREQUAL CONTENT)
    file(WRITE "${OUTPUT}" "${CONTENT}")
endif()
